# Chap 4, Independence

## Summary
Firstly, we defined the definition of independence (of 2 events)

Then:

-   The independence of finite events
-   The independence of finite classes (collection of events)
-   The independence of arbitrary number of classes, by focusing of all
    the finite subset
-   Further, if the independent classes are $\pi$-system, then the
    $\sigma$-field then generated are also independent

Then we go to the measurable function part, and for a R.V X, we focus on
the $\sigma$-field it generates, $\sigma(X)$.

Secondly, we have grouping on a collection of independent $\sigma$-field

-   If we divide an index set into mutually disjoint subsets, then the
    $\sigma$-fields generated associated to these subset index are
    independent.

Thirdly, we have the 0-1 laws.

-   Borel: for independent events $\{A_n\}$,if we want to study its
    limsup, $[A_n\; i.o.]$, we can try study $\sum_{n}P(A_n)$
-   Kolmogorov: for independent R.Vs $\{X_n\}$, the information from
    infinity is almost trivial, and independent to the information of
    all the $\{X_n\}$.

## Ex 10

::: problem
Suppose $\{X_n,\ n\ge 1\}$ are independent random variables. Show that
$$
P\!\left(\sup_{n\ge 1} X_n < \infty\right)=1
\quad\text{iff}\quad
\sum_{n=1}^\infty P(X_n > M) < \infty \ \text{for some } M.
$$
:::

$\textbf{My idea:}$ $\Rightarrow$: Suppose $\forall$ $m\in R^+$, we have
$\sum_{n}P[X_n>m]=\infty$, that is, we have
$P[X_n>m ,\: \text{i.o.}]=1$, also, $[X_n=\infty]=\bigcap_{m}[X_n>m]$,
that is, $P[X_n=\infty,\:\text{i.o.}]=1$, which is contradicted to
$\sum_n P[\sup_n X_n<\infty]=1$. $\Leftarrow$: now we have for some $M$,
$\sum_{n}P[X_n>M]<\infty$, according to Borel 0-1 law, we have
$P[X_n>M,\: \text{i.o.}]=0$, that is $P[\lim\inf[X_n\leq M]]=1$, so
there $\exists N$, such that for $n\geq N$, we have $P[X_n\leq M]=1$
therefore we have $P[\sup X_n<\infty]=1$

$\textbf{Answer:}$ $\Rightarrow$: Suppose $\forall m\in N^+$, we have
$\sum_{n}P[X_n>m]=\infty$, that is, by Borel–Cantelli II (using
independence), we have $P[X_n> m ,\: \text{i.o.}]=1$, that is,
$P(\bigcap_{m=1}^\infty\{X_n> m,\:\text{i.o.}\})=1$ and
$\bigcap_{m=1}[X_n> m,\:\text{i.o.}]\subset \{\omega,\:\sup X_n(\omega)=\infty\}$,
since $\{\omega,\:\sup X_n(\omega)=\infty\}$ means: for any $m\geq0$,
exists $n(\omega,m)>0$, such that $X_n(\omega)>m$, written in set form,
it is: $\bigcap_m\bigcup_n[X_n>m]$, so we have
$P(\{\omega,\:\sup X_n(\omega)=\infty\})=1$, which leads to
contradiction. $\Leftarrow$: now we have for some $M$,
$\sum_{n}P[X_n>M]<\infty$, according to Borel-contelli,
$P[X_n>M,\:\text{i.o.}]=0$, that is $P(\lim\inf_n[X_n\leq M])=1$, that
is,
$P(\bigcup_{N\geq1}\bigcap_{n\geq N}\{\omega,\:X_n(\omega)\leq M\})=1$,
so if
$\omega\in\bigcup_{N\geq1}\bigcap_{n\geq N}\{\omega,\:X_n(\omega)\leq M\}$,
then for this fixed $\omega$, exists a $N(\omega)$, such that for
$n\geq N(\omega)$, we have $X_n(\omega)\leq M$, so for a.e $\omega$, we
have
$\sup_n X_n(\omega)=\max(\max_{1\leq n<N(\omega)}X_n(\omega),M)<\infty$.

$\textbf{Notes:}$

1.  in general, we don't swap the order of $\bigcap$ and $\bigcup$.
2.  $\sup_n X_n=\infty$ in $\varepsilon-N$ language: for any $m>0$,
    exists an $n(\omega,m)$, such that $X_n>m$.

## Ex 11

::: problem
Use the Borel--Cantelli Lemma to prove that, given any sequence of
random variables $\{X_n,\ n\ge 1\}$ whose range is the real line, there
exist constants $c_n\to\infty$ such that 
$$
P\!\left(\lim_{n\to\infty}\frac{X_n}{c_n}=0\right)=1.
$$ 
Give a careful description of how you choose $c_n$.
:::

$\textbf{My idea:}$ if we want to find $\{c_n\}$ that
$P[\lim_{n\to\infty}\frac{X_n}{c_n}=0]$, think the opposite, that is,
for any $a>0$, we must have $P[\frac{X_n}{c_n}>a\ \text{i.o.}]=0$,
because if such $\{c_n\}$ exists, $X_n$ would not exceed any positive
number infintely many times, so we just need to fix some $a>0$, and
construct $\{c_n\}$ such that make sure
$\sum_{n=1}^{\infty} P[X_n>a\cdot c_n]<\infty$, so I try to make it
shrink as $\frac{1}{2^n}$, then I may choose $c_n=\sup_n X_n\cdot2^n$.

$\textbf{Answer:}$ We need to guarantee that for any $k\in N^+$,
$P[\frac{X_n}{c_n}>\frac{1}{k}\ \text{i.o.}]=0$ so that
$\frac{X_n}{c_n}\to0\ \text{a.s.}$, since
$\{\frac{X_n}{c_n}\not\to0\}=\bigcup_{k\geq1}\{\frac{X_n}{c_n}>\frac{1}{k}\ \text{i.o.}\}$,
according to Borel-contelli I, we start from
$\sum_{n=1}^{\infty} P(|X_n|>\frac{c_n}{k}<\infty)$, since $\{X_n\}$ are
r.v., so we have $P(|X_n|>t)\to0\ (t\to\infty)$, that is, for $2^{-n}$,
exists a $t_n$, such that $P(|X_n|>t_n)\leq2^{-n}$, now if we want
$\frac{c_n}{k}\geq t_n$ for any fixed $k\in N^+$, we can set
$c_n=n\cdot t_n$, so $\frac{c_n}{k}=\frac{n\cdot t_n}{k}\geq t_n$, so we
have $\sum_{n}P(|X_n|>\frac{c_n}{k})<\infty$, thus
$P[\lim_n\frac{X_n}{c_n}=0]=1$.

$\textbf{Notes:}$ The diagonal trick: we want for any $k$, $c_n$
satisfies $\frac{c_n}{k}>t_n$, that is we have 2 directions: $n$ and $k$
in a $\infty\times\infty$ matrix, then for each $k$, our $n$ can move
along in the triangle $n\geq k$, to make sure that
$\frac{n\cdot t_n}{k}\geq t_n$.

## Ex 12

::: problem
Let $\{a_n\}$ and $\{b_n\}$ be nonnegative sequences such that $$
\lim_{n\to\infty}\frac{a_n}{b_n}=1.
$$ Show that 
$$
\sum_{n=1}^\infty a_n<\infty \quad\text{iff}\quad \sum_{n=1}^\infty b_n<\infty.
$$
:::

$\textbf{My idea:}$ In this problem, we can just discuss one direction
("$\Rightarrow$"), then we can use $\lim_{n\to\infty}\frac{b_n}{a_n}=1$
to prove another direction. Since we have
$\lim_{n\to\infty}\frac{a_n}{b_n}=1$ and $\sum_{n}a_n<\infty$ and
$\{a_n\}$, $\{b_n\}$ are non-negative sequences, without lost of
generality, we can assume that $\{a_n\},\ \{b_n\}\in[0,1]$, otherwise we
can discuss the terms after some big $N$. We can assign $\{a_n\}$ as
probability to independent measurable set $\{A_n\}$ and $\{b_n\}$ to
$\{B_n\}$, where $\{B_n\}$ also independent, then we have
$\sum_{n}P(A_n)<\infty$, so $P[A_n\ \text{i.o.}]=0$, since
$\lim_{n\to\infty}\frac{a_n}{b_n}=1$, we know that
$P[B_n\ \text{i.o.}]=0$, so we get $\sum_{n}b_n=\sum_{n}P(B_n)<\infty$.

$\textbf{Answer:}$ Since $\lim_{n\to\infty}\frac{a_n}{b_n}=1$, then
$\forall\varepsilon>0$, $\exists N>0$ such that when $n>N$,
$(1-\varepsilon)b_n<a_n<(1+\varepsilon)b_n$, the sequences are
non-negative, then we can choose $\varepsilon\in(0,1)$ to have
$\sum_{n\geq N}b_n\leq\frac{\sum_{n\geq N}a_n}{1-\varepsilon}<\infty$
and $\sum_{n\geq N}a_n\leq(1+\varepsilon)\sum_{n\geq N}b_{n}<\infty$.

$\textbf{What's wrong:}$ I focus too much on the 0-1 law, which is
unnecessary, just use the classic analysis method, this exercise just
want to tell us that, when facing complicated $\{A_n\}$ with prob
$\{a_n\}$, we can choose {b_n} to discuss 0-1 law on it. And also,
Constructing independent events is not a valid step.

## Ex 13
::: problem
Let $\{X_n,\ n\ge 1\}$ be i.i.d. with $$
P(X_1=1)=p=1-P(X_1=0).
$$ What is the probability that the pattern $1,0,1$ appears infinitely
often?

Hint: Let $$
A_k=\{X_k=1,\ X_{k+1}=0,\ X_{k+2}=1\}
$$ and consider $A_1, A_4, A_7, \ldots$.
:::

$\textbf{My idea:}$ Using the hint, let
$A_k=[X_k=1,\ X_{k+1}=0,\ X_{k+2}=1]$, $\{A_k\}$ are not independent,
but $A_{3k+1}$ are independent since $\{X_n\}$ iid, also, we have
$P(A_{3k+1})=p^2(1-p)$, which is a constant, so
$\sum_{k\geq0}P(A_{3k+1})=\infty$, that is,
$P[A_{3k+1}\ \text{i.o.}]=1$, so the pattern 1,0,1 appears infinitely
often with probability 1.

$\textbf{Answer:}$ Start from $P(A_{3k+1})=p^2(1-p)$, we need to check
the edge case: $p\in (0,1)$ and $p\in\{0,1\}$, for the former, we have
$\sum_{k\geq0}P(A_{3k+1})=\infty$, but for the latter, we have
$\sum_{k\geq0}P(A_{3k+1})=0$, so the pattern 1,0,1 appears infinitely
often with probability 1 when $p\in (0,1)$, with probability 0 when
$p\in\{0,1\}$.

$\textbf{Notes:}$ Just remember to check the edge cases.

## Ex 14

::: problem
In a sequence of independent Bernoulli random variables
$\{X_n,\ n\ge 1\}$ with $$
P(X_n=1)=p=1-P(X_n=0),
$$ let $A_n$ be the event that a run of $n$ consecutive $1$'s occurs
between the $2^n$ and $2^{n+1}$st trial. If $p\ge \tfrac12$, then there
is probability $1$ that infinitely many $A_n$ occur.

\medskip

Hint: Prove something like 
$$
P(A_n)\ge 1-(1-p^n)^{2^n/2n} > 1-e^{-(2p)^n/2n}.
$$
:::

$\textbf{My idea:}$ I figure out that, for each $n$, there will then
$2^{n+1}-2^{n}=2^n$ elements from $2^{n+1}$ to $2^n$, if we exclude the
left endpoint to make sure each interval are disjoint, and
$P(A_n)=p^n(1-p)^{2^n-n}(2^n-n+1)$ since there will be $2^n-n+1$
consecutive sequences with length $n$.

$\textbf{Answer:}$ For each $n$, there will then $2^{n+1}-2^{n}=2^n$
elements from $2^{n}$ to $2^{n+1}$, if we exclude the left endpoint to
make sure each interval are disjoint, and there will be at least
$\lfloor\frac{2^n}{n}\rfloor$ disjoint consecutive sequence for each
$A_n$, to find the probability that these are 1's (and the rest can be 0
or 1), is to use 1 minus the probability that these sequences are not
all 1's, that is $1-(1-p^n)^{\lfloor\frac{2^n}{n}\rfloor}$, using the
hint, we have $$
P(A_n)\geq 1-(1-p^n)^{\lfloor\frac{2^n}{n}\rfloor}>1-\exp(-\frac{(2p)^n}{2n})
$$ For exponential part, it converges to $0$ when $p\geq1/2$, so
$P(A_n)\geq 1/2$ when $n$ is large, therefore $\sum_nP(A_n)=\infty$ so
there will be infinitely many $A_n$ occur by Borel-Cantelli II since
each $A_n$ are independent.

$\textbf{Note:}$ How many disjoint sequences with length $n$ in each
$A_n$ at least? $\left\lfloor\frac{2^n}{n}\right\rfloor$. For each
length-$n$ sequence, $1-p^n$ is the probability that it is \emph{not}
all $1$'s. Since these sequences are disjoint (hence independent), $$
(1-p^n)^{\left\lfloor\frac{2^n}{n}\right\rfloor}
$$ is the probability that all these sequences are \emph{not} all $1$'s.
Therefore, $$
1-(1-p^n)^{\left\lfloor\frac{2^n}{n}\right\rfloor}
$$ is the probability that at least one of these sequences is all $1$'s.

## Ex 15

::: problem
$\textbf{(a)}$ A finite family $\{\mathcal{B}_i,\ i\in I\}$ of
$\sigma$-algebras is independent iff for every choice of non-negative
$\mathcal{B}_i$-measurable random variables $Y_i$, $i\in I$, we have $$
E\!\left(\prod_{i\in I} Y_i\right)=\prod_{i\in I} E(Y_i).
$$ (One direction is immediate. For the opposite direction, prove the
result first for positive simple functions and then extend.)

\medskip

$\textbf{(b)}$ If $\{\mathcal{B}_t,\ t\in T\}$ is an arbitrary
independent family of $\sigma$-algebras in $(\Omega,\mathcal{B},P)$, the
family $\{\mathcal{B}'_t,\ t\in T\}$ is again independent if
$\mathcal{B}_t \supset \mathcal{B}'_t$ $(t\in T)$. Deduce from this that
$\{f_t(X_t),\ t\in T\}$ is a family of independent random variables if
the family $\{X_t,\ t\in T\}$ is independent and the $f_t$ are
measurable. In order for the family $\{X_t,\ t\in T\}$ of random
variables to be independent, it is necessary and sufficient that $$
E\!\left(\prod_{j\in J} f_j(X_j)\right)=\prod_{j\in J} E\!\left(f_j(X_j)\right)
$$ for every finite family $\{f_j,\ j\in J\}$ of bounded measurable
functions.
:::

### (a)
$\textbf{My idea:}$ In each $\sigma$-algebra $B_i$, we define a
indicator function $Y_i=1_{A_i}$, where $A_i\in B_i$, so $Y_i$ is a
$B_i$-measurable R.V., $$
E(\prod_{i\in I}Y_i)=E(\prod_{i\in I} 1_{A_i})=E(1_{\bigcap_{i\in I}A_i})=\prod_{i\in I}\mu(A_i)=\prod_{i\in I}E(Y_i),
$$ where $\mu$ is the measure for each $\sigma$-algebra, if $Y_i$'s are
simple function, the expectation of their product is the product in
measure of interception of measurable set, so we also have
$E(\prod_{i\in I}Y_i)=\prod_{i\in I}E(Y_i)$, since $I$ is finite, then
for any $B_i$-measurable function $Y_i$, it can be approximated by
$B_i$-measurable simple function sequence, and if $Y_i$'s are
integrable, also $\prod{i\in I}Y_i$, so the order of product and
limitation can be changed. Conversely, if we have
$E(\prod_{i\in I}Y_i)=\prod_{i\in I}E(Y_i)$, then let each $Y_i$ be
simple function, we can get the $B_i$ are independent.

$\textbf{Answer:}$ In each $\sigma$-algebra $B_i$, we define a indicator
function $Y_i=\mathbf{1}_{A_i}$, where $A_i\in B_i$, so $Y_i$ is a
$B_i$-measurable R.V., $$
E(\prod_{i\in I}Y_i)=E(\prod_{i\in I} \mathbf{1}_{A_i})=E(1_{\bigcap_{i\in I}A_i})=\prod_{i\in I}P(A_i)=\prod_{i\in I}E(Y_i),
$$ then we discuss the situation when $Y_i$'s are simple function
$Y_i=\sum_{j=1}^{n_i}c_{ij}\mathbf{1}_{A_{ij}}$, where $c_{ij}\geq0$, we
can rewrite the product of $Y_i$ as
$\prod_{i\in I}Y_i=\prod_{i\in I}(\sum_{j=1}^{n_i}c_{ij}\mathbf{1}_{A_{ij}})=\sum_{j}(\prod_{i\in I}c_{ij})\mathbf{1}_{\bigcap_{i\in I}A_{ij}}$,
so for simple funcion, we also have
$E(\prod_{i\in I}Y_i)=\prod_{i\in I}E(Y_i)$, then for any non-negative
$B_i$-measurable function $Y_i$, for each $i$, we can find a sequence of
non-negative simple function $Y_i^{(m)}$ such that
$Y_i^{(m)}\uparrow Y_i$, and by using monotone convergence theorem,
$E(Y_i^{(m)})\uparrow E(Y_i)$, so for finitely many product of
measurable function, we also have
$E(\prod_{i\in I}Y_i)=\prod_{i\in I}E(Y_i)$, Conversely, if we have
$E(\prod_{i\in I}Y_i)=\prod_{i\in I}E(Y_i)$, then let each $Y_i$ be
indicator function, we can get the $B_i$ are independent.

### (b)
$\textbf{My idea:}$ when $f_j$ is an indicator, such as
$f_j=\mathbf{1}_{A_j}$ for some $A_j\in\mathcal{B}_j$, then we have
$E(f_j(X_j))=E[\mathbf{1}_{A_j}(X_j)]=P[X_j\in A_j]$, so we have $$
E(\prod_J f_j(X_j))=\prod_{J}E(f_j(X_j)),
$$ , using the same idea in (a), for any bounded measurable functions
$\{f_j,\ j\in J\}$, we have $E(\prod_J f_j(X_j))=\prod_{J}E(f_j(X_j))$.
Conversely, if we have $E(\prod_J f_j(X_j))=\prod_{J}E(f_j(X_j))$,for
any bounded measurable functions $\{f_j,\ j\in J\}$, by letting
$f_j(x)=x$, and according to (a), we have for any finite index set $J$,
$\{X_j,\ j\in J\}$ are independent, and therefore $\{X_t,\ t\in T\}$ are
independent for arbitrary index set.

$\textbf{Answer:}$ Firstly, for $\{\mathcal{B}_t,\ t\in T\}$ when
$\mathcal{B'}_t\subset\mathcal{B}_t$, then for any
$A_t\in\mathcal{B'}_t$, it's in $\mathcal{B}_t$, so $\{A_t,\ t\in T\}$
are independent by the independence of $\{\mathcal{B}_t,\ t\in T\}$,
therefore $\{\mathcal{B'}_t,\ t\in T\}$ are independent. When $f_j$ is
an indicator, such as $f_j=\mathbf{1}_{A_j}$ for some
$A_j\in\mathcal{B}(\mathbb{R})$, then we have
$E(f_j(X_j))=E[\mathbf{1}_{A_j}(X_j)]=P[X_j\in A_j]$, so we have $$
E(\prod_J f_j(X_j))=\prod_{J}E(f_j(X_j)),
$$ using the same idea in (a), for any bounded measurable functions
$\{f_j,\ j\in J\}$, we have $E(\prod_J f_j(X_j))=\prod_{J}E(f_j(X_j))$,
since $\sigma(f_j(X_j))\subseteq\sigma(X_j)$, so
$\{\sigma(f_j(X_j)),\ j\in J\}$ are independent . Conversely, if we have
$E(\prod_J f_j(X_j))=\prod_{J}E(f_j(X_j))$,for any bounded measurable
functions $\{f_j,\ j\in J\}$, by letting $f_j(x)=\mathbf{1}_{A_j}$, for
some $A_j\in\mathcal{B}(\mathbb{R})$. then we have
$E(\prod_J f_j(X_j))=E(\prod_J \mathbf{1}_{\{X_j\in A_j\}})=\prod_J E(\mathbf{1}_{\{X_j\in A_j\}})$,
then we have $P(\bigcap_J \{X_j\in A_j\})=\prod_J P(\{X_j\in A_j\})$,
which we get for any finite index set $J$, $\{X_j,\ j\in J\}$ are
independent, and therefore $\{X_t,\ t\in T\}$ are independent for
arbitrary index set.

$\textbf{Note:}$ When we construct $f_j$ as indicator, $A_j$ is not in
$\mathcal{B}_j$, but in $\mathcal{B}(\mathbb{R})$ since $X_j$ is R.V. so
its range is in $\mathbb{R}$, it is because in this book, we only
consider real-valued measurable function.

## Ex 16

::: problem
The probability of convergence of a sequence of independent random
variables is equal to $0$ or $1$. If the sequence $\{X_n\}$ is i.i.d.,
and not constant with probability $1$, then 
$$
P[X_n\ \text{converges}]=0.
$$
:::

$\textbf{My idea:}$ Suppose for iid, not a.e constant r.v. sequence
$\{X_n\}$, we have $P[X_n\ \text{converges}]\neq0$, since the event
$[X_n\ \text{converges}]\in\mathcal{T}$, so we have
$P[X_n\ \text{converges}]=1$, that is, exist random variable $X$, such
that $X_n\to X$ a.e, however, $X\in\mathcal{T}$ also, so there exists a
constant $c$, such that $P[X=c]=1$, this is contradicted to the fact
that $\{X_n\}$ is not constant with probability 1.

$\textbf{Answer:}$ Suppose for iid, not a.e constant r.v. sequence
$\{X_n\}$, we have $P[X_n\ \text{converges}]\neq0$, since the event
$[X_n\ \text{converges}]\in\mathcal{T}$, so we have
$P[X_n\ \text{converges}]=1$, that is, exist random variable $X$, such
that $X_n\to X$ a.e, however, $X\in\mathcal{T}$ also, according to Lemma
4.5.1 so there exists a constant $c$, such that $P[X=c]=1$, that is,
$X_n\to c$ a.e, therefore for any $\varepsilon>0$,
$P(|X_n-c|>\varepsilon)\to0,\ (n\to\infty)$, and $\{X_n\}$ is iid, then
the probability is the same for all $n$, that is to say, for any
$\varepsilon>0$, we have $P(|X_n-c|>\varepsilon)=0$, this is
contradicted to the fact that $\{X_n\}$ is not constant with probability
1.

$\textbf{Lemma (Resnick Lemma 4.5.1).}$ If $\mathcal{G}$ is almost
trivial (i.e. $P(A)\in\{0,1\}$ for all $A\in\mathcal{G}$) and $X$ is
$\mathcal{G}$-measurable, then $X=c$ a.s. for some constant $c$.

$\textbf{Note:}$ When we get $X_n\to c$ a.e, we need to prove that
$X_n=c$ a.e using the iid statement.

## Ex 17

::: problem

$\textbf{(a)}$ Suppose $\{X_n,\ n\ge 1\}$ are iid random variables and suppose $\{a_n\}$ is a
sequence of constants. Show
\[
P\big(\{X_n>a_n\}\ \text{i.o.}\big)=
\begin{cases}
0, & \text{if }\displaystyle\sum_{n} P[X_1>a_n]<\infty,\\[6pt]
1, & \text{if }\displaystyle\sum_{n} P[X_1>a_n]=\infty .
\end{cases}
\]

$\textbf{(b)}$ Suppose $\{X_n,\ n\ge 1\}$ are iid $N(0,1)$ random variables. Show
\[
P\!\left[\limsup_{n\to\infty}\frac{|X_n|}{\sqrt{\log n}}=\sqrt{2}\right]=1.
\]
$\textit{Hint:}$ Review, or look up Mill's Ratio which says
\[
\lim_{x\to\infty}\frac{P[X_n>x]}{\phi(x)/x}=1,
\]
where $\phi(x)$ is the standard normal density.

$\textbf{(c)}$ Suppose $\{X_n,\ n\ge 1\}$ are iid and Poisson distributed with parameter $\lambda$.
Prove
\[
\frac{\lambda^n}{n!}e^{-\lambda}\le P[X_1\ge n]\le \frac{\lambda^n}{n!},
\]
and therefore
\[
P\!\left[\limsup_{n\to\infty}\frac{X_n}{\log n/\log(\log n)}=1\right]=1.
\]
:::

### (a)
$\textbf{My idea:}$ Let $A_n=[X_n>a_n]$, since $\{X_n,\ n\geq1\}$ are
iid r.v's, then $A_n=[X_1>a_n]$, according to Borel-Cantelli II, we get
what we want.

$\textbf{Answer:}$ Let $A_n=[X_n>a_n]$, since $\{X_n,\ n\geq1\}$ are iid
r.v's, then $P(A_n)=P(X_n>a_n)=P(X_1>a_n)$, and $\{A_n\}$ are
independent, then according to Borel-Cantelli, $P[A_n\ \text{i.o.}]=1$
iff $\sum_n P(X_1>a_n)=\infty$ and $P[A_n\ \text{i.o.}]=0$ iff
$\sum_n P(X_1>a_n)<\infty$.

$\textbf{Note:}$ $A_n=[X_n>a_n]$, is not equal to $[X_1>a_n]$, but we
only need to discuss it probability.

### (b)
$\textbf{My idea:}$ For $\omega\in\Omega$, if
$\limsup_{n\to\infty}\frac{|X_n|}{\sqrt{\log n}}=\sqrt2$, it means

1.  $\forall\varepsilon>0$,
    $\frac{|X_n|}{\sqrt{\log n}}\leq\sqrt2+\varepsilon$ for large $n$,

2.  $\forall\varepsilon>0$,
    $\frac{|X_n|}{\sqrt{\log n}}>\sqrt2-\varepsilon$ for infinitely many
    $n$.

That is, by letting $\varepsilon_k\downarrow0$, we have 
$$
\begin{aligned}
\left[\limsup_{n\to\infty}\frac{|X_n|}{\sqrt{\log n}}=\sqrt2\right]
&= \bigcap_{k=1}^\infty \left(\liminf_{n\to\infty}\left[\frac{|X_n|}{\sqrt{\log n}}\le \sqrt2+\varepsilon_k\right]\right)
\ \bigcap\
\bigcap_{k=1}^\infty \left[\frac{|X_n|}{\sqrt{\log n}}>\sqrt2-\varepsilon_k\ \text{i.o.}\right].
\end{aligned}
$$

Then we can discuss
$P[\frac{|X_n|}{\sqrt{\log n}}>\sqrt2-\varepsilon_k]$, using the Mill's
Ratio, we have
$P[\frac{|X_n|}{\sqrt{\log n}}>\sqrt2-\varepsilon_k]\sim2\frac{\phi((\sqrt2-\varepsilon_k)\sqrt{\log n})}{(\sqrt2-\varepsilon_k)\sqrt{\log n}}=\frac{2}{n^{\frac{(\sqrt{2}-\varepsilon_k)^2}{2}}\sqrt{\log n}(\sqrt{2}-\varepsilon_k)}$.

That is, we have $\frac{(\sqrt{2}-\varepsilon_k)^2}{2}<1$, for all $k$,
therefore
$\sum_{n\to\infty}P[\frac{|X_n|}{\sqrt{\log n}}>\sqrt2-\varepsilon_k]=\infty$,
so
$P\left[\frac{|X_n|}{\sqrt{\log n}}>\sqrt2-\varepsilon_k\ \text{i.o.}\right]=1$.

For the $\liminf$ part, we can discuss the probability of its
complement, which is $$
\begin{aligned}
P\left\{\limsup_{n\to\infty}\left[\frac{|X_n|}{\sqrt{\log n}}\le \sqrt2+\varepsilon_k\right]^c\right\}&=P\left\{\limsup_{n\to\infty}\left[\frac{|X_n|}{\sqrt{\log n}}> \sqrt2+\varepsilon_k\right]\right\}\\
&=P\left[\frac{|X_n|}{\sqrt{\log n}}> \sqrt2+\varepsilon_k\ \text{i.o.}\right]\\
&\sim 2\frac{\phi((\sqrt2+\varepsilon_k)\sqrt{\log n})}{(\sqrt2+\varepsilon_k)\sqrt{\log n}}\\
&=\frac{2}{n^{\frac{(\sqrt{2}+\varepsilon_k)^2}{2}}\sqrt{\log n}(\sqrt{2}+\varepsilon_k)}
\end{aligned}
$$ and we have
$\sum_{n\to\infty}\frac{2}{n^{\frac{(\sqrt{2}+\varepsilon_k)^2}{2}}\sqrt{\log n}(\sqrt{2}+\varepsilon_k)}<\infty$
since $\frac{(\sqrt{2}+\varepsilon_k)^2}{2}>1$, so
$P\left[\frac{|X_n|}{\sqrt{\log n}}> \sqrt2+\varepsilon_k\ \text{i.o.}\right]=0$,
so for any $k$, we have
$P\left\{\liminf_{n\to\infty}\left[\frac{|X_n|}{\sqrt{\log n}}\le \sqrt2+\varepsilon_k\right]\right\}=1$,
according to the above, we have $$
P\left[\limsup_{n\to\infty}\frac{|X_n|}{\sqrt{\log n}}=\sqrt2\right]=1
$$ $\textbf{Answer:}$ For $\omega\in\Omega$, if
$\limsup_{n\to\infty}\frac{|X_n|}{\sqrt{\log n}}=\sqrt2$, it means

1.  $\forall\varepsilon>0$,
    $\frac{|X_n|}{\sqrt{\log n}}\leq\sqrt2+\varepsilon$ for large $n$,

2.  $\forall\varepsilon>0$,
    $\frac{|X_n|}{\sqrt{\log n}}>\sqrt2-\varepsilon$ for infinitely many
    $n$.

That is, by letting $\varepsilon_k\downarrow0$, we have 
$$
\begin{aligned}
\left[\limsup_{n\to\infty}\frac{|X_n|}{\sqrt{\log n}}=\sqrt2\right]
&= \bigcap_{k=1}^\infty \left(\liminf_{n\to\infty}\left[\frac{|X_n|}{\sqrt{\log n}}\le \sqrt2+\varepsilon_k\right]\right)
\ \bigcap\
\bigcap_{k=1}^\infty \left[\frac{|X_n|}{\sqrt{\log n}}>\sqrt2-\varepsilon_k\ \text{i.o.}\right].
\end{aligned}
$$

Then we can discuss
$P[\frac{|X_n|}{\sqrt{\log n}}>\sqrt2-\varepsilon_k]$, using the Mill's
Ratio, we have
$P[\frac{|X_n|}{\sqrt{\log n}}>\sqrt2-\varepsilon_k]\sim2\frac{\phi((\sqrt2-\varepsilon_k)\sqrt{\log n})}{(\sqrt2-\varepsilon_k)\sqrt{\log n}}=\frac{2}{n^{\frac{(\sqrt{2}-\varepsilon_k)^2}{2}}\sqrt{\log n}(\sqrt{2}-\varepsilon_k)}$.

Let
$A_n^{-}(k)=\left[\frac{|X_n|}{\sqrt{\log n}}>\sqrt2-\varepsilon_k\right]$.
Since $\{X_n\}$ are independent, $\{A_n^{-}(k)\}$ are independent. Also,
$$
\sum_{n=1}^\infty P(A_n^{-}(k))
=\sum_{n=1}^\infty P\!\left(\frac{|X_n|}{\sqrt{\log n}}>\sqrt2-\varepsilon_k\right)
=\infty.
$$ Hence by Borel--Cantelli II, $$
P\big(A_n^{-}(k)\ \text{i.o.}\big)=1.
$$

For the $\liminf$ part, we can discuss the probability of its
complement, which is $$
\begin{aligned}
P\left\{\limsup_{n\to\infty}\left[\frac{|X_n|}{\sqrt{\log n}}\le \sqrt2+\varepsilon_k\right]^c\right\}&=P\left\{\limsup_{n\to\infty}\left[\frac{|X_n|}{\sqrt{\log n}}> \sqrt2+\varepsilon_k\right]\right\}\\
&=P\left[\frac{|X_n|}{\sqrt{\log n}}> \sqrt2+\varepsilon_k\ \text{i.o.}\right].\\
\end{aligned}
$$ Let
$A_n^{+}(k)=\left[\frac{|X_n|}{\sqrt{\log n}}>\sqrt2+\varepsilon_k\right]$.
Then $$
\sum_{n=1}^\infty P(A_n^{+}(k))
=\sum_{n=1}^\infty P\!\left(\frac{|X_n|}{\sqrt{\log n}}>\sqrt2+\varepsilon_k\right)
<\infty,
$$ since $\frac{(\sqrt{2}+\varepsilon_k)^2}{2}>1$. Hence by
Borel--Cantelli I, $$
P\big(A_n^{+}(k)\ \text{i.o.}\big)=0,
$$ equivalently, 
$$
P\left\{\liminf_{n\to\infty}\left[\frac{|X_n|}{\sqrt{\log n}}\le \sqrt2+\varepsilon_k\right]\right\}=1.
$$ According to the above, we have 
$$
P\left[\limsup_{n\to\infty}\frac{|X_n|}{\sqrt{\log n}}=\sqrt2\right]=1
$$

$\textbf{Note:}$ 1. Should not write:
$P[\text{something i.o.}]\sim 2\frac{\phi(\dots)}{\dots}$, 2. Should
specifically state Borel-Cantelli. 3. Should state the independence of
the event.

### (c)
$\textbf{My idea:}$ We knew that for Poisson distribution,
$P[X_1\geq n]=\sum_{k=n}^{\infty}\frac{\lambda^k}{k!}\exp(-\lambda)\geq\frac{\lambda^n}{n!}\exp(-\lambda)$,
for the other direction

Using the same method from (b) and example 4.5.2, we only need to
discuss two summation: 
$$
\sum_{n}P\left[\frac{X_n}{\log n/\log(\log n)}\geq 1-\varepsilon_k\right]\ \text{and}\ 
\sum_{n}P\left[\frac{X_n}{\log n/\log(\log n)}\geq 1+\varepsilon_k\right].
$$ 
For the first one, we have 
$$
\sum_{n}P\left[X_n\geq (1-\varepsilon_k)({\frac{\log n}{\log(\log n)}})\right]\geq\sum_{n}\frac{\lambda^{((1-\varepsilon_k)({\frac{\log n}{\log(\log n)}}))}}{\lceil(1-\varepsilon_k)({\frac{\log n}{\log(\log n)}})\rceil!},
$$ 
the ${\frac{\log n}{\log(\log n)}}$ part basically act as a constant,
so we can only consider $\lambda^{(1-\varepsilon_k)}$, therefore we have
$\sum_{n}P\left[X_n\geq (1-\varepsilon_k)({\frac{\log n}{\log(\log n)}})\right]\geq\sum_{n}\frac{\lambda^{((1-\varepsilon_k)({\frac{\log n}{\log(\log n)}}))}}{\lceil(1-\varepsilon_k)({\frac{\log n}{\log(\log n)}})\rceil!}=\infty$.

For the second one, we have $$
\sum_{n}P\left[X_n\geq (1+\varepsilon_k)({\frac{\log n}{\log(\log n)}})\right]\leq\sum_{n}\frac{\lambda^{((1+\varepsilon_k)({\frac{\log n}{\log(\log n)}}))}}{\lceil(1+\varepsilon_k)({\frac{\log n}{\log(\log n)}})\rceil!},
$$ by the same idea, we can conclude that
$\sum_{n}P\left[X_n\geq (1+\varepsilon_k)({\frac{\log n}{\log(\log n)}})\right]<\infty$.

According to the above, we have
$P\left[\limsup_{n\to\infty}\frac{X_n}{\log n/\log(\log n)}=1\right]=1$.

$\textbf{Answer:}$ We knew that for Poisson distribution,
$P[X_1\geq n]=\sum_{k=n}^{\infty}\frac{\lambda^k}{k!}\exp(-\lambda)\geq\frac{\lambda^n}{n!}\exp(-\lambda)$,
for the other direction, we define $(X)_n=X(X-1)(X-2)\dots(X-n+1)$, then
we have: (1) when $X<n$, then exist some $k<n$, such that $X-k=0$, so
$(X)_n=0$, that is, $(X)_n\geq n!\mathbf{1}_{\{X\geq n\}}$, (2) when
$X\geq n$, then $X\geq n,\ X-1\geq n-1,\dots,\ X-n+1\geq 1$, so
$(X)_n\geq n!$, therefore we have
$(X)_n\geq n!\mathbf{1}_{\{X\geq n\}}$, and
$\mathbf{1}_{\{X\geq n\}}\leq\frac{(X)_n}{n!}$, then we have $$
P(X\geq n)=E(\mathbf{1}_{{\{X\geq n\}}})\leq \frac{E((X)_n)}{n!},
$$ also, 
$$
\begin{aligned}
E((X)_n)&=\exp(-\lambda)\sum_{k=0}^\infty (k)_n\frac{\lambda^k}{k!}\\
&=\exp(-\lambda)\sum_{k=n}^\infty \frac{\lambda^k}{(k-n)!}\ (\text{Because}\ (k)_n=k(k-1)\dots(k-n+1))\\
&=\exp(-\lambda)\sum_{m=0}^\infty \frac{\lambda^{m+n}}{m!}\ (\text{By letting}\ m=k-n)\\
&=\lambda^n
\end{aligned}
$$ so we have $P(X\geq n)\leq\frac{\lambda^n}{n!}$.

Using the same method from (b) and example 4.5.2, we only need to
discuss two summation: 
$$
\sum_{n}P\left[\frac{X_n}{\log n/\log(\log n)}\geq 1-\varepsilon_k\right]\ \text{and}\ 
\sum_{n}P\left[\frac{X_n}{\log n/\log(\log n)}\geq 1+\varepsilon_k\right].
$$
We can define $m_n:=\lceil c\,\frac{\log n}{\log\log(n)}\rceil$ and then
try to discuss the properties of $\frac{\lambda^{m_n}}{m_n!}$ using the
first part of the question, for this, we can use the Stirling's formula
in log form: $\log(n!)=n\log n-n+\frac{1}{2}\log(2\pi n)+o(1)$. Let
$T(m_n)=\frac{\lambda^{m_n}}{m_n!}$, then 
$$
\begin{aligned}
\log T(m_n)&=m_n\log\lambda-\log(m_n!)\\
&=m_n\log\lambda-(m_n\log(m_n)-m_n+\frac{1}{2}\log(m_n)+o(1))\\
&=-m_n\log(m_n)-\frac{1}{2}\log(m_n)+(1+\log\lambda)m_n+o(1),\\
\end{aligned}
$$ 
Also, we can discuss $\log(m_n)$ $$
\log(m_n)=\log c+\log\log n-\log\log\log n=\log\log n+o(\log\log n),
$$ combine the above together, we have 
$$
\begin{aligned}
\log T(m_n)&=-c\frac{\log n}{\log\log n}(\log\log n+o(\log\log n))-\frac{1}{2}[\log\log n+o(\log\log n)]+
(1+\log\lambda)c\frac{\log n}{\log\log n}+o(1)\\
&=-c\log n+o(\log n)-\frac{1}{2}[\log\log n+o(\log\log n)]+
(1+\log\lambda)c\frac{\log n}{\log\log n}+o(1)\\
&=-c\log n+o(\log n),
\end{aligned}
$$ 
so we have $T(m_n)=\exp(-c\log n+o(\log n))=n^{-c+o(1)}$, since $o(1)\to 0,$ for any $\delta>0$, eventually $n^{-c+o(1)}\leq n^{-(c-\delta)}$ and $n^{-c+o(1)}\geq n^{-(c+\delta)}$, so we can choose $\delta$, such that
for $c=1+\varepsilon_k$,
$\sum_n n^{-(1+\varepsilon_k)+o(1)}\leq \sum_n n^{-(1+\varepsilon_k-\delta)}<\infty$, and for
$c=1-\varepsilon_k$, $\sum_n n^{-(1-\varepsilon_k)+o(1)}\geq\sum_n n^{-(1-\varepsilon_k+\delta)}=\infty$.
And since $X_n$ iid, so the events are independent, using Borel-Cantelli I and II, we
have
$P\left[\limsup_{n\to\infty}\frac{X_n}{\log n/\log(\log n)}=1\right]=1$.

$\textbf{Note:}$ When facing the problem to estimate the order of $n!$, try to connect to Striling's formula:
$$
n!\sim\sqrt{2\pi}n^{n+\frac{1}{2}}\exp(-n).
$$
My idea fails because the growth is dominated by $m_n!$, where $m_n=\lceil c\,\frac{\log n}{\log\log(n)}\rceil$.

## Ex 18

::: problem
If the event $A$ is independent of the $\pi$-system $\mathcal{P}$ and $A\in\sigma(\mathcal{P})$, then $P(A)$ is either $0$ or $1$.
:::


$\textbf{My idea:}$ We know that $\{A\}$ is a $\pi$-system, and since event $A$ is independent of $\mathcal{P}$, then $\{A\}$ is independent of $\mathcal{P}$, so $\sigma(\{A\})$ is independent of $\sigma(\mathcal{P})$, and $A$ is in both of them, so $A$ is independent of itself, $P(A)$ is either $0$ or $1$.

$\textbf{Answer:}$ We know that $\{A\}$ is a $\pi$-system, and since event $A$ is independent of $\mathcal{P}$, then $\{A\}$ is independent of $\mathcal{P}$, so according to Theorem 4.1.1, $\sigma(\{A\})$ and $\sigma(\mathcal{P})$ are independent, and $A$ is in both of them, so $A$ is independent of itself, 
$$
P(A)=P(A\cap A)=P(A)P(A)=P(A)^2,
$$
$P(A)$ is either $0$ or $1$.

$\textbf{Note:}$ My idea is right, but I should have cited Theorem 4.1.1.


## Ex 19

::: problem
\ Give a simple example to show that 2 random variables may be independent according to one probability measure but dependent with respect to another.
:::

$\textbf{My idea:}$ For 2 fair coins, define $P[X=1]=P[X=0]=P[Y=1]=P[Y=0]=\frac{1}{2}$, then $X$, $Y$ are iid, however we can define the joint distribution as $P[X=1,Y=1]=P[X=0,Y=0]=\frac{1}{2}$, and $P[X=1,Y=0]=P[X=0,Y=1]=0$, so they are not independent with respect to another probability.

$\textbf{Answer:}$ Rewrite the idea part in a clean way:
Firstly, take the sample space $\Omega=\{0,1\}^2$ and $\mathcal{F}=2^\Omega$, then define random variables $X(\omega_1,\omega_2)=\omega_1, Y(\omega_1,\omega_2)=\omega_2$.
After that, we define two probability measures:

1. Probability measure P:
$$
P(\{(i,j)\})=\frac{1}{4},\qquad (i,j)\in\Omega.
$$
2. Diagonal measure Q:
$$
Q(\{(1,1)\})=Q(\{(0,0)\})=\frac{1}{2},\quad Q(\{(1,0)\})=Q(\{(0,1)\})=0.
$$
Then for measure $P$, we have $P(X=i)=P(Y=j)=\frac{1}{2},\ P(X=i,Y=j)=\frac{1}{4}$, so $P(X=i,Y=j)=P(X=i)P(Y=j)$ ,$(i,j)\in\Omega$. However, for measure $Q$, we have $Q(X=1)=Q(Y=1)=\frac{1}{2}$, and $Q(X=1,Y=1)=\frac{1}{2}\neq Q(X=1)Q(Y=1)$.


$\textbf{Note:}$ 1. When we discuss random variables, we should clarify in what sample space, 2. We should use different notations to represent different probability measures. In this question, we are required to discuss 2 probability measures in 1 sample space.

## Ex 20

::: problem
\ Counterexamples and examples:

a) Let $\Omega=\{1,2,3,4\}$ with each point carrying probability $1/4$. Let $A_1=\{1,2\},\ A_2=\{1,3\},\ A_3=\{1,4\}$. Then any two of $A_1,A_2,A_3$ are independent, but $A_1,A_2,A_3$ are not independent.

b) Let $\{A_i,\ 1\le i\le 5\}$ be a measurable partition of $\Omega$ such that $P(A_1)=P(A_2)=P(A_3)=15/64,\ P(A_4)=1/64,\ P(A_5)=18/64$. Define
$B=A_1\cup A_4,\ C=A_2\cup A_4,\ D=A_3\cup A_4$. Check that
\[
P(BCD)=P(B)P(C)P(D)
\]
but that $B,\ C,\ D$ are not independent.

c) Let $X_1,X_2$ be independent random variables each assuming only the values $+1$ and $-1$ with probability $1/2$. Are $X_1,X_2,X_1X_2$ pairwise independent? Are $X_1,X_2,X_1X_2$ an independent collection?
:::

$\textbf{My idea:}$ 

### (a) We have $P(A_i)=\frac{1}{2},\ i=1,2,3$ and $P(A_i\cap A_j)=P(\{1\})=\frac{1}{4}=P(A_i)P(A_j),\ i\neq j$, and $P(A_1\cap A_2\cap A_3)=P(\{1\})=\frac{1}{4}\neq P(A_1)P(A_2)P(A_3)=\frac{1}{8}$.

### (b)We have
$$
\begin{aligned}
P(BCD)&=P((A_1\cup A_4)\cap(A_2\cup A_4)\cap(A_3\cup A_4))\\
&=P((A_1\cap A_2\cap A_3)\cup A_4)=P(\varnothing\cup A_4)\\
&=P(A_4)=\frac{1}{64},
\end{aligned}
$$
$P(B)=P(C)=P(D)=\frac{16}{64}=\frac{1}{4}$, so $P(B)P(C)P(D)=\frac{1}{64}$, further, $P(BC)=P(BD)=P(CD)=P(A_4)=\frac{1}{64}$, and $P(B)P(C)=P(B)P(D)=P(C)P(D)=\frac{1}{16}$, so $B,C,D$ are not independent.

### (c)Let $Y=X_1X_2$, $P(Y=1)=P(X_1=1,X_2=1)+P(X_1=-1,X_2=-1)=P(X_1=1)P(X_2=1)+P(X_1=-1)P(X_2=-1)=\frac{1}{2}$ and $P(Y=-1)=P(X_1=1,X_2=-1)+P(X_1=-1,X_2=1)=P(X_1=1)P(X_2=-1)+P(X_1=-1)P(X_2=1)=\frac{1}{2}$. Since we already knew that $X_1$ and $X_2$ are independent, by the symmetry, we can only discuss the independence between $X_1$ and $Y=X_1X_2$, so we have 
$$
\begin{aligned}
&P(X_1=1,X_1X_2=1)=P(X_1=1,X_2=1)=\frac{1}{4}\\
&P(X_1=1,X_1X_2=-1)=P(X_1=1,X_2=-1)=\frac{1}{4}\\
&P(X_1=-1,X_1X_2=1)=P(X_1=-1,X_2=-1)=\frac{1}{4}\\
&P(X_1=-1,X_1X_2=-1)=P(X_1=-1,X_2=1)=\frac{1}{4},\\
\end{aligned}
$$
so $X_1$ and $Y$ are independent, however, we have $P(X_1=1,X_2=1,X_1X_2=-1)=0$, but $P(X_1=1)P(X_2=1)P(X_1X_2=-1)=\frac{1}{8}\neq0$.

$\textbf{Note:}$ I think this part is good.


## Ex 21

::: problem
\ Suppose $\{A_n\}$ is a sequence of events.

(a) If $P(A_n)\to 1$ as $n\to\infty$, prove there exists a subsequence $\{n_k\}$ tending to infinity such that
$P\!\left(\bigcap_k A_{n_k}\right)>0$. (Hint: Use Borel--Cantelli.)

(b) Show the following is false: Given $\varepsilon>0$ such that $P(A_n)\ge \varepsilon$, it follows that there exists a subsequence $\{n_k\}$ tending to infinity such that
$P\!\left(\bigcap_k A_{n_k}\right)>0$.
:::

### (a)

$\textbf{My idea:}$ Suppose for any subsequence $\{n_k\}$ that tending to infinity, we have $P(\cap_k A_{n_k})=0$, that is, for any $k$, we have $P(\cap_{n=k}^{\infty}A_n)=0$, so we have $P(\liminf_{n\to\infty}A_n)=P(\cup_{k=1}^\infty\cap_{n=k}^{\infty}A_n)\leq\sum_{k=1}^\infty P(\cap_{n=k}^{\infty}A_n)=0$, however, since $P(A_n)\to 1\ (n\to\infty)$, and $P$ is continuous from above and below, so $P(\liminf_{n\to\infty}A_n)$ should be $1$.

$\textbf{Answer:}$ From $P(A_n)\to1\ (n\to\infty)$ we have $P(A_n^c)\to0\ (n\to\infty)$, that is, we can select a subsequence $\{n_k\}$ that is tending to infinity, such that $P(A_{n_k}^c)\leq2^{-(k+1)}$ for all $k$, then we have for any $m$,
$$
P(\bigcap_{k=1}^{m}A_{n_k})=1-P(\bigcup_{k=1}^{m}A_{n_k}^c)\geq 1-\sum_{k=1}^m P(A_{n_k}^c)\geq1-\sum_{k=1}^m2^{-(k+1)}\geq\frac{1}{2}
$$
Since $P$ is continuous from above, so $P(\cap_{k}A_{n_k})=\lim_{m\to\infty}P(\cap_{k=1}^{m}A_{n_k})\geq\frac{1}{2}$.

$\textbf{Note:}$ From $P(A_n)\to1$, we may not have $P(\liminf_{n\to\infty}A_n)=1$.


### (b) 

$\textbf{My idea:}$ My idea is just that when $A_n$ are mutually disjoint, then it cannot happen.

$\textbf{Answer:}$ Consider flipping a fair coin, let $\Omega=\{0,1\}^\mathbb{N}$, and $A_n=\{\omega_n=1\}$, so $P(A_n)=\frac{1}{2}$ for any $n$, however for any subsequence $\{n_k\}$ that is tending to infinity, we have $P(\bigcap_{k}A_{n_k})=\lim_{m\to\infty} P(\bigcap_{k=1}^{m}A_{n_k})=\lim_{m\to\infty}\frac{1}{2^m}=0$.

$\textbf{Note:}$ If exist $\varepsilon$ such that $P(A_n)\geq\varepsilon$, they cannot be mutually disjoint since $P(\bigcup_{n}A_n)=\sum_n P(A_n)\geq \sum_n\varepsilon=\infty$.


## Ex 22
::: problem
\ Suppose $\{A_n\}$ are independent events such that
\[
\sum_{n=1}^{\infty}\bigl(P(A_n)\wedge(1-P(A_n))\bigr)=\infty.
\]
Show $P$ is non-atomic.
:::

$\textbf{My idea:}$ Suppose $P$ is atomic, that is exist $A\in\mathcal{B}$, for all $B\in\mathcal{B}$ and $B\subseteq A$, either $P(B)=0$ or $P(A\setminus B)=0$. So W.L.G, suppose $A_i$ is an atom, that is $P(A_n)>0$, then for any $j\neq i$, we have $A_i\cap A_j\subseteq A_i$, so either $P(A_i\cap A_j)=0$, in this case, because they are independent, we have $P(A_i)P(A_j)=0$, for all $j\neq i$, or $P(A_i\(A_i\cap A_j))=0$, in this case, we have $P(A_i\(A_i\cap A_j))=P(A_i)(1-P(A_j))=0$, that is $(1-P(A_j))=0$, so for $j\neq i$, if $P$ is atomic, either $P(A_j)=0$ or $1-P(A_j)=0$, which is contradicted to $\sum_{n=1}^\infty\left(\min(P(A_n),1-P(A_n))\right)=\infty$, therefore $P$ should be non-atomic.

$\textbf{Answer:}$ Suppose $P$ is atomic, and let $E$ be the atom, so we have $P(E)>0$, and for each $A_n$, either $P(E\cap A_n)=0$ or $P(E\setminus(E\cap A_n))=P(E\cap A_n^c)=0$, then we can define $\{B_n\}$ as 
$$
B_n=
\begin{cases}
A_n, & \text{if } P(E\cap A_n^c)=0 \quad (\text{so }E\subseteq A_n\ \text{a.s.})\\
A_n^c, & \text{if } P(E\cap A_n)=0 \quad (\text{so }E\subseteq A_n^c\ \text{a.s.})
\end{cases}
$$
let $B=\bigcap_{n=1}^\infty B_n$, and we have $P(E)=P(E\cap B)+P(E\cap B^c)$, however, according to the definition of $B_n$, we have 
$$
\begin{aligned}
P(E\cap B^c)&=P\left(E\cap(\bigcap_{n=1}^\infty B_n)^c\right)\\
&=P\left(E\cap(\bigcup_{n=1}^\infty B_n^c)\right)\\
&=P\left(\bigcup_{n=1}^\infty (E\cap B_n^c)\right)\\
&\leq\sum_{n=1}^\infty P(E\cap B_n^c)=0.

\end{aligned}
$$
So we have $P(E)=P(E\cap B)\leq P(B)$.

For any fixed $m$, we have $P\left(\bigcap_{n=1}^m B_n\right)=\prod_{n=1}^m r_n$ where $r_n\in\{P(A_n), 1-P(A_n)\}$, so $r_n\leq 1-q_n$, where $q_n=\min(P(A_n), 1-P(A_n))$, then $\sum_{n}q_n=\infty$ and using the fact that $\log(1-q_n)\leq -q_n$, we have $\prod_n (1-q_n)=0$ .Then for $P(B)$, we have $P(B)=P\left(\bigcap_{n=1}^\infty B_n \right)=\lim_{m\to\infty}P\left(\bigcap_{n=1}^m B_n \right)\leq\lim_{m\to\infty}\prod_{n=1}^m (1-q_n)=0$, Since an atom must have positive probability, we get the contradiction which leads to the conclusion that $P$ is non-atomic.

$\textbf{Note:}$ We cannot assume that some $A_n$ is the atom, instead, we make the atom interact with each $A_n$, then the infinite sum of minimum make sure that no atom can survive the infinite intersection of independent events.


## Ex 23

::: problem
\ Suppose $\{A_n\}$ are events.

(a) If for each $k$
\[
\sum_{n=k}^{\infty} P\!\left(A_n \,\middle|\, \bigcap_{i=k}^{\,n-1} A_i^{c}\right)=\infty,
\]
show
\[
P\!\left(\limsup_{n\to\infty} A_n\right)=1.
\]

(b) What is the relevance to the Borel Zero-One Law?

(c) Is it enough to assume
\[
\sum_{n=1}^{\infty} P\!\left(A_n \,\middle|\, \bigcap_{i=1}^{\,n-1} A_i^{c}\right)=\infty\ ?
\]

(d) Show
\[
P\!\left(\limsup_{n\to\infty} A_n\right)=1
\]
iff
\[
\sum_{n=1}^{\infty} P(A\cap A_n)=\infty
\]
for all events $A$ such that $P(A)>0$.
:::

### (a)
$\textbf{My idea:}$ My idea is that since we want to show $P[A_n\ \text{i.o.}]=1$, and we have
$$
P[A_n\ \text{i.o.}]=1-\lim_{n\to\infty}\lim_{m\to\infty}P(\bigcap_{k=n}^mA_k^c),
$$
and link this to 
$$
P(A_n|\bigcap_{i=k}^{n-1}A_i^c)=\frac{P(A_n\cap\bigcap_{i=k}^{n-1}A_i^c)}{P(\bigcap_{i=k}^{n-1}A_i^c)}
$$

$\textbf{Answer:}$ Firstly, we have
$$
P[A_n\ \text{i.o.}]=1-\lim_{k\to\infty}\lim_{m\to\infty}P(\bigcap_{n=k}^mA_n^c),
$$
fix $k$, define $B_n:=\bigcap_{i=k}^nA_i^c$, and follow the convention, $B_{k-1}=\Omega$, therefore we have
$$
\begin{aligned}
P(B_n)&=P(A_n^c\cap\bigcap_{i=k}^{n-1}A_i^c)=P(A_n^c\cap B_{n-1})\\
&=P(B_{n-1})P(A_n^c|B_{n-1})=P(B_{n-1})(1-P(A_n|B_{n-1})),
\end{aligned}
$$
then for any $m$, we have
$$
\begin{aligned}
P(\bigcap_{n=k}^mA_n^c)&=P(B_m)\\
&=P(B_{m-1})(1-P(A_m|B_{m-1}))\\
&=P(B_{m-2})(1-P(A_{m-1}|B_{m-2}))(1-P(A_m|B_{m-1}))\\
&\dots\\
&=P(B_{k-1})(1-P(A_{k}|B_{k-1}))(1-P(A_{k+1}|B_{k}))\dots(1-P(A_{m-1}|B_{m-2}))(1-P(A_m|B_{m-1}))\\
&=\prod_{n=k}^{m}(1-P(A_n|B_{n-1}))\\
&=\prod_{n=k}^{m}(1-P(A_n|\bigcap_{i=k}^{n-1}A_i^c))\leq\exp(-\sum_{n=k}^mP(A_n|\bigcap_{i=k}^{n-1}A_i^c))\to0\ (m\to\infty).
\end{aligned}
$$
In the last step, we use the fact that since for each $k$, $\sum_{n=k}^\infty P(A_n|\bigcap_{i=k}^{n-1}A_i^c)=\infty$, and $1-x\leq\exp(-x)$ for $0<x<1$. So $P[A_n\ \text{i.o.}]=1$.

$\textbf{Note:}$ I didn't figure out the recursive relation.

### (b)
$\textbf{My idea:}$ The conditional part makes the event independent.

$\textbf{Answer:}$ $[A_n\ \text{i.o.}]=\limsup_{n\to\infty}A_n$ is a tail event, according to Borel zero-one law, its probability can only be $0$ or $1$, and the condition in (a) exclude $0$, so it can only be $1$.


### (c)
$\textbf{My idea:}$  We just need to find an event sequence such that $\sum_{n=1}^\infty P(A_n|\bigcap_{i=1}^{n-1}A_i^c)=\infty$, but $P[A_n\ \text{i.o.}]=0$, and this sequence cannot be independent, or else the Borel zero-one law will enforce $P[A_n\ \text{i.o.}]=1$.

$\textbf{Answer:}$ Let $T$ follows geometric distribution with parameter $p\in(0,1)$, and let $A_n=\{T=n\}$, so $P(A_n|\bigcap_{i=1}^{n-1} A_i^c)=P(T=n|T\geq n)=p$, $\sum_{n=1}^\infty P(A_n|\bigcap_{i=1}^{n-1} A_i^c)=\sum_{n=1}^\infty p=\infty$, however, $A_n$ can occur at most once, so $P[A_n\ \text{i.o.}]=0$, therefore only $\sum_{n=1}^\infty P(A_n|\bigcap_{i=1}^{n-1} A_i^c)=\infty$ is not enough.

$\textbf{Note:}$ For memoryless distribution T, we can make $P(A_n|\bigcap_{i=1}^{n-1} A_i^c)$ to be constant, but $A_n$ can only occur at most once.

### (d)
$\textbf{My idea:}$ The converse part is obvious since by letting $A=\Omega$, we have $P(A)=1>0$, by Borel-Cantelli's lemma, $\sum_{n=1}^\infty P(A\cap A_n)=\sum_{n=1}^\infty P(A_n)=\infty$ implies $P[A_n\ \text{i.o.}]=1$. For another direction, since $P[A_n\ \text{i.o.}]$, that is, for each $\omega\in\Omega$, exist a sub-sequence $n_k(\omega)$, such that $A_{n_k}$ occur, then for $A\cap A_n$, $P(A)>0$, they can also happen infinitely many times, so $\sum_{n=1}^\infty P(A\cap A_n)=\infty$.

$\textbf{Answer:}$ $\Rightarrow$: suppose exists $A_0\in\mathcal{B}$, such that $P(A_0)>0$ and $\sum_{n=1}^\infty P(A_0\cap A_n)<\infty$, then according to Borel-Cantelli's lemma, we have $P[A_0\cap A_n\ \text{i.o}]=0$, however, 
$$
\begin{aligned}
P[A_0\cap A_n\ \text{i.o}]&=P(\limsup_{n\to\infty}A_0\cap A_n)\\
&=P(A_0\cap\limsup_{n\to\infty} A_n)\\
&=P(A_0)-P(A_0\cap(\limsup_{n\to\infty} A_n)^c)\\
&=P(A_0)-0\\
&=0,
\end{aligned}
$$
which is contradicted to $P(A_0)>0$ so for any $P(A)>0$, we have $\sum_{n=1}^\infty P(A\cap A_n)=\infty$.

$\Leftarrow$: Suppose $P[A_n\ \text{i.o.}]<1$, then let $A=(\limsup_{n\to\infty}A_n)^c=\liminf_{n\to\infty}A_n^c$, so we have $P(A)>0$, since $A=\bigcup_{k=1}^\infty\bigcap_{n=k}^\infty A_n^c$, $A$ is the countable union of $B_k=\bigcap_{n=k}^\infty A_n^c$, so exist some $k$, such that $P(B_k)>0$, however $\sum_{n=1}^\infty P(B_k\cap A_n)=\sum_{n=1}^{k-1}P(B_k\cap A_n)<\infty$, which contradicts to the assumption that for all $A$ such that $P(A)>0$, $\sum_{n=1}^\infty P(A\cap A_n)=\infty$, so we have $P[A_n\ \text{i.o.}]=1$.


## Ex 24

::: problem
\ If $P(A_n)\ge \varepsilon>0$, for all large $n$, then $P(A_n\ \text{i.o.})\ge \varepsilon$.
:::

$\textbf{My idea:}$ Since for large $n$, $P(A_n)\geq\varepsilon$, that is, exist $N>0$ such that when $n\geq N$, we also have $P(\bigcup_{m\geq n}A_m)\geq\varepsilon$, since $\{\bigcup_{m\geq n}A_m\}_{n\geq1}$ is a decreasing sequence, so $P[A_n\ \text{i.o.}]=P(\bigcap_{n=1}^\infty\bigcup_{m\geq n}A_m)=\lim_{n\to\infty}P(\bigcup_{m\geq n}A_m)\geq\varepsilon$.

$\textbf{Note:}$ I am basically correct this time.

## Ex 25

::: problem
\ Use Renyi's theorem to prove that if $\{X_n,\ n\ge 1\}$ is iid with common continuous distribution
\[
P\!\left(\left[X_n=\bigvee_{i=1}^{n} X_i\right]\ \text{i.o.}\right)=1.
\]
:::

$\textbf{My idea:}$ Let $A_n=[X_n=\max\{X_i,i=1,\dots,n\}]$, since $\{X_n\}$ is iid with common continuous distribution, $A_n$ means that $X_n$ is a record, according to Renyi's theorem, $\{A_n\}$ is independent and $P(A_n)=\frac{1}{n}$, that is, we have $\sum_{n=1}^\infty P(A_n)=\infty$, according to BC II, $=P\{[X_n=\max\{X_i,i=1,\dots,n\}]\ \text{i.o.}\}=P[A_n\ \text{i.o.}]=1$.

$\textbf{Note:}$ I am basically correct this time.

## Ex 26

::: problem
\ (Barndorff-Nielsen)} Suppose $\{E_n\}$ is a sequence of events such that
$$ \lim_{n \to \infty} P(E_n) = 0, \quad \sum_{n} P(E_n E_{n+1}^c) < \infty. $$
Prove
$$ P(E_n \text{ i.o.}) = 0. $$
Hint: Decompose $\bigcup_{j=n}^m E_j$ for $m > n$.
:::

$\textbf{My idea:}$ For $\bigcup_{j=n}^mE_j$, $m>n$, we have 
$$
\begin{aligned}
\bigcup_{j=n}^mE_j&=\bigcup_{j=n}^{m-1}\{(E_j\cap E_{j+1})\cup(E_j\cap E_{j+1}^c)\}\cup E_m\\
&=\bigcup_{j=n}^{m-1}(E_j\cap E_{j+1})\cup\bigcup_{j=n}^{m-1}(E_j\cap E_{j+1}^c)\cup E_m\\
&=\left\{\bigcup_{j=n}^{m-1}E_j\cap\bigcup_{j=n}^{m-1}E_{j+1}\right\}\cup\bigcup_{j=n}^{m-1}(E_j\cap E_{j+1}^c)\cup E_m,
\end{aligned}
$$
therefore, for $P(\bigcup_{j=n}^mE_j)$, we have 
$$
\begin{aligned}
P(\bigcup_{j=n}^mE_j)\leq P\left(\left\{\bigcup_{j=n}^{m-1}E_j\cap\bigcup_{j=n}^{m-1}E_{j+1}\right\}\right)+P(\bigcup_{j=n}^{m-1}(E_j\cap E_{j+1}^c))+P(E_m)
\end{aligned}
$$
since we have $\lim_{n\to\infty}P(E_n)=0$ and $\sum_n P(E_n\cap E_{n+1}^c)\leq\infty$, so when $n$ and $m$ approach to infinity, the right hand side goes to $0$, that is $\lim_{n\to\infty}\lim_{m\to\infty}P(\bigcup_{j=n}^mE_j)=0$, and that is exactly $P[E_n\ \text{i.o.}]=0$.


$\textbf{Answer:}$ For $\bigcup_{j=n}^mE_j$, $m>n$, we have 
$$
\begin{aligned}
\bigcup_{j=n}^mE_j&=\bigcup_{j=n}^{m-1}\{(E_j\cap E_{j+1})\cup(E_j\cap E_{j+1}^c)\}\cup E_m\\
&=\bigcup_{j=n}^{m-1}(E_j\cap E_{j+1})\cup\bigcup_{j=n}^{m-1}(E_j\cap E_{j+1}^c)\cup E_m\\
&=\bigcup_{j=n}^{m-1}(E_j\cap E_{j+1}^c)\cup E_m,
\end{aligned}
$$
in the last two step, for any $\omega\in\bigcup_{j=n}^{m-1}(E_j\cap E_{j+1})$ there will be at least one $k\in\{n,\dots,m-1\}$ such that $\omega\in E_k\cap E_{k+1}$, so $S(\omega)=\{j\in\{n,\dots, m\}:\ \omega\in E_j\}$ is non-empty, then it is legal to let $L$ be the largest index such that $\omega\in E_L$, so 1. $L=m$, then $\omega\in E_m$, 2. $n\leq L<m$, then we know that $\omega\in E_L$ and $\omega\not\in E_{L+1}$, that is $\omega\in E_L\cap E_{L+1}^c$, so in both cases, $\omega\in\bigcup_{j=n}^{m-1}(E_j\cap E_{j+1}^c)\cup E_m$, that is, the term $\bigcup_{j=n}^{m-1}(E_j\cap E_{j+1})$ is absorbed by $\bigcup_{j=n}^{m-1}(E_j\cap E_{j+1}^c)\cup E_m$.

Therefore,
$$
P(\bigcup_{j=n}^mE_j)\leq P(\bigcup_{j=n}^{m-1}(E_j\cap E_{j+1}^c))+P(E_m).
$$
By letting $m\to\infty$, and because $P$ is continuous from below, we have 
$$
\begin{aligned}
P(\bigcup_{j=n}^{\infty}E_j)&\leq P(\bigcup_{j=n}^{\infty}(E_j\cap E_{j+1}^c))+\lim_{m\to\infty}P(E_m)\\
&=P(\bigcup_{j=n}^{\infty}(E_j\cap E_{j+1}^c))+0\\
&=P(\bigcup_{j=n}^{\infty}(E_j\cap E_{j+1}^c)),
\end{aligned}
$$
that is, for $P[E_n\ \text{i.o.}]$, by continuous from above, we have
$$
\begin{aligned}
P[E_n\ \text{i.o.}]&=P(\bigcap_{n=1}^{\infty}\bigcup_{j=n}^\infty E_j)\\
&=\lim_{n\to\infty}P(\bigcup_{j=n}^\infty E_j)\\
&\leq\lim_{n\to\infty}P(\bigcup_{j=n}^{\infty}(E_j\cap E_{j+1}^c))\\
&\leq\lim_{n\to\infty}\sum_{j=n}^\infty P(E_j\cap E_{j+1}^c)=0.
\end{aligned}
$$
In the last step, $\lim_{n\to\infty}\sum_{j=n}^\infty P(E_j\cap E_{j+1}^c)=0$ since $\sum_{n=1}^\infty P(E_n\cap E_{n+1}^c)<\infty$.

$\textbf{Note:}$ For the decomposition part, we can just consider the telescope absorption:
$$
\bigcup_{j=n}^mE_j=\bigcup_{j=n}^{m-1}(E_j\cap E_{j+1}^c)\cup E_m.
$$
and the condition can be interpret as: the element eventually stop staying in the sequence.


## Ex 27

::: problem
\ If $\{X_n, n\ge 1\}$ are independent random variables, show that the radius of
convergence of the power series $\sum_{n=1}^{\infty} X_n z^n$ is a constant (possibly infinite)
with probability one.

\medskip
Hint: The radius of convergence of $\sum_{n=1}^{\infty} c_n z^n$ is given by
\[
R^{-1}=\limsup_{n\to\infty} |c_n|^{1/n}.
\]
:::

$\textbf{My idea:}$ Let $Y_n=\sup|X_n|^{1/n}$, since $\{X_n\}$ are independent r.v.s then $Y_n$ are also independent r.v.s, so $\limsup_{n\to\infty}Y_n\in\mathcal{T}$, that means $\limsup_{n\to\infty}Y_n$ is a constant with probability $1$, so the radius of convergence of the power series is a constant with probability one, when $\limsup_{n\to\infty}Y_n=0$ with probability one, then the radius is infinity with probability one.

$\textbf{Answer:}$ Let $Y_n=|X_n|^{1/n}$, so we have $R(\omega)^{-1}=\limsup_{n\to\infty}|X_n|^{1/n}=\limsup_{n\to\infty}Y_n$, since $\{X_n\}$ are independent r.v.s then $Y_n$ are also independent r.v.s, and for $\limsup_{n\to\infty}Y_n$, the $\limsup$ for $\{Y_1,Y_2,\dots\}$ is the same as the $\limsup$ for $\{Y_{m+1},Y_{m+2},\dots\}$ for any $m\geq1$, so $\limsup_{n\to\infty}Y_n\in\mathcal{T}$, then for event $\{\limsup_{n\to\infty}Y_n\leq a\}=\{\limsup_{n\geq m+1}Y_n\leq a\}\in\sigma(\{Y_{m+1},Y_{m+2},\dots\})$, for any $m$, so $\{\limsup_{n\to\infty}Y_n\leq a\}\in\bigcap_{m}\sigma(\{Y_{m+1},Y_{m+2},\dots\})=\mathcal{T}$, according to Kolmogorov's 0-1 law, it can only have probability $0$ or $1$, so by letting $c=\inf\{q\in\mathbb{Q}:\ P(\limsup_{n\to\infty}Y_n\leq q)=1\}$, we have $\limsup_{n\to\infty}Y_n=c$ with probability one, since for $q\in\mathbb{Q}$, if $q<c$, $P(\limsup_{n\to\infty}Y_n\leq q)=0$, if $q>c$, $P(\limsup_{n\to\infty}Y_n\leq q)=1$. So $R=\frac{1}{c}\ \text{a.s.}$ (with $1/0=\infty$ and $1/\infty=0$).

$\textbf{Note:}$ We should clarify the logic chain of this question, let $L:=R^{-1}=\limsup_{n\to\infty}|X_n|^{1/n}$, then:
1. $L$ is a random varible, and is $\mathcal{T}$-measurable
2. $L$ is a constant in probability one.
3. The radius is a constant in probability one.
Each step above should be stated clearly in the proof.

## Ex 28

::: problem
\ Show $\{X_n,\, n\ge 1\}$ are independent if
\[
\sigma(X_1,\ldots,X_{n-1}) \perp\!\!\!\perp \sigma(X_n)
\]
are independent for each $n\ge 2$.
:::

$\textbf{My idea:}$ Since for each $n\geq2$, $\sigma(X_1,\dots,X_{n-1})$ and $\sigma(X_n)$ are independent, then we know: $\sigma(X_1)$ and $\sigma(X_2)$ are independent, when $n=2$, and when $n=3$, 
$\sigma(X_1,X_{2})$ and $\sigma(X_3)$ are independent, so we have $\sigma(X_1)$ and $\sigma(X_3)$ are independent, and $\sigma(X_{2})$ and $\sigma(X_3)$ are independent since $\sigma(X_1),\sigma(X_2)\subseteq\sigma(X_1,X_{2})$, that is, $\sigma(X_1)$, $\sigma(X_2)$ and $\sigma(X_3)$ are pairwisely independent, then for any fixed $n$, $\{\sigma(X_n)\}$ are pairewise independent. Further, for any finite subset $A=\{a_1,\dots,a_n\}$ of $\mathbb{N}$, $\{\sigma(X_i),\ i\in A\}$ are independent since for $a_i<a_j$, we have $\sigma(X_1,\dots,X_{a_i},\dots,X_{a_j-1})$ and $\sigma(X_{a_j})$ are independent, and $\sigma(X_{a_i})\subseteq\sigma(X_1,\dots,X_{a_i},\dots,X_{a_j-1})$, therefore $\{\sigma(X_n)\}$ are independent, so $\{X_n,\ n\geq1\}$ are independent by the definition of independence of r.v.s.

$\textbf{Answer:}$ For any fixed $n$, and any $A_i\in\sigma(X_i)$, $i=1,\dots,n$, since $\sigma(X_1,\dots,X_{n-1})$ and $\sigma(X_n)$ are independent, we have $P(\bigcap_{i=1}^nA_i)=P(\bigcap_{i=1}^{n-1}A_i)P(A_n)$, because $\bigcap_{i=1}^{n-1}A_i\in\sigma(X_1,\dots,X_{n-1})$ and $A_n\in\sigma(X_n)$, however, we also have $\bigcap_{i=1}^{n-2}A_i\in\sigma(X_1,\dots,X_{n-2})$ and $A_{n-1}\in\sigma(X_{n-1})$, and $\sigma(X_1,\dots,X_{n-2})$ and $\sigma(X_{n-1})$ are also independent, so $P(\bigcap_{i=1}^{n-1}A_i)=P(\bigcap_{i=1}^{n-2}A_i)P(A_{n-1})$, that is $P(\bigcap_{i=1}^nA_i)=P(\bigcap_{i=1}^{n-2}A_i)P(A_{n-1})P(A_n)$, repeat the same argument for $P(\bigcap_{i=1}^{n-2}A_i)$, etc. Formally, by induction on $n$, we have $P(\bigcap_{i=1}^nA_i)=\prod_{i=1}^{n}P(A_i)$, therefore $\sigma(X_1),\dots,\sigma(X_n)$ are independent for every $n$, so $\{X_n,\ n\geq1\}$ are independent by the definition of independence of r.v.s.

$\textbf{Note:}$ I was wrong about the definition of independent classes, so I type it here:

$\textbf{Definition (Independent classes)}$ Let $\mathcal{C}_i\subseteq\mathcal{B}$, $i=1,\dots,n$.
The classes $\mathcal{C}_i$ are independent, if for any choice $A_1,\dots,A_n$, with
$A_i\in \mathcal{C}_i$, $i=1,\dots,n$, we have the events $A_1,\dots,A_n$ independent events.

## Ex 29

::: problem
 Let
\[
\Omega=\{1,\ldots,r\}^n=\{(x_1,\ldots,x_n): x_i\in\{1,\ldots,r\},\, i=1,\ldots,n\}
\]
and assume an assignment of probabilities such that each point of $\Omega$ is equally likely.
Define the coordinate random variables
\[
X_i((x_1,\ldots,x_n))=x_i,\qquad i=1,\ldots,n.
\]
Prove that the random variables $X_1,\ldots,X_n$ are independent.
:::

$\textbf{My idea:}$ According to the assumption, we have $|\Omega|=r^n$, so each point $\omega\in\Omega$ has probability $\frac{1}{r^n}$, and for coordinate random variables, $X_i(\omega)=X_i((x_1,\dots,x_n))=x_i$, $i=1,\dots,n$, then for $x_i\in\{1,\dots,r\}$, $P(X_i=x_i)=\frac{r^{n-1}}{r^n}=\frac{1}{r}$, because for the numerator, there are $r^{n-1}$ situations, then for r.v.s $X_1,\dots,X_n$, and any $\omega=(x_1,x_2,\dots,x_n)\in\Omega$,by corollary 4.2.2 we have
$$
P(X_1=x_1,\dots,X_n=x_n)=\frac{1}{r^n}=\prod_{i=1}^{n}P(X_i=x_i),
$$
therefore $X_1,\dots,X_n$ are independent.

## Ex 30

::: problem
Refer to Subsection 4.3.2.

(a) Define
\[
A=\{[d_{2n}=0]\ \text{i.o.}\}, \qquad B=\{[d_{2n+1}=1]\ \text{i.o.}\}.
\]
Show $A \perp\!\!\!\perp B$.

(b) Define
\[
l_n(\omega):=\text{length of the run of $0$'s starting at } d_n(\omega),
\]
\[
l_n(\omega)=
\begin{cases}
k\ge 1, & \text{if } d_n(\omega)=0,\ldots,d_{n+k-1}(\omega)=0,\ d_{n+k}(\omega)=1,\\
0, & \text{if } d_n(\omega)=1.
\end{cases}
\]
Show
\[
P[l_n=k]=\left(\frac12\right)^{k+1}, \qquad P[l_n\ge r]=\left(\frac12\right)^r. \tag{4.18}
\]

(c) Show $\{[l_n=0],\, n\ge 1\}$ are independent events.

(d) Show $P([l_n=0]\ \text{i.o.})=1$. (Use the Borel Zero-One Law.)

(e) The events $\{[l_n=1],\, n\ge 1\}$ are not independent but the events
$\{[l_{2n}=1],\, n\ge 1\}$ are, and therefore prove
\[
P([l_{2n}=1]\ \text{i.o.})=1
\]
so that
\[
P([l_n=1]\ \text{i.o.})=1.
\]

(f) Let $\log_2 n$ be the logarithm to the base $2$ of $n$. Show
\[
P\!\left[\limsup_{n\to\infty}\frac{l_n}{\log_2 n}\le 1\right]=1. \tag{4.19}
\]
\textbf{Hint:} Show
\[
\sum_n P\!\left[l_n>(1+\varepsilon)\log_2 n\right]<\infty
\]
and use Borel-Cantelli. Then replace $\varepsilon$ by $\varepsilon_k\downarrow 0$.

(g) Show
\[
P\!\left[\limsup_{n\to\infty}\frac{l_n}{\log_2 n}\ge 1\right]=1.
\]
Combine this with (4.19).

Hint: Set $r_n=[\log_2 n]$ and define $n_k$ by
$n_1=1$, $n_2=1+r_1$, \ldots, $n_{k+1}=n_k+r_{n_k}$ so that
$n_{k+1}-n_k=r_{n_k}$. Then
\[
[l_{n_k}\ge r_{n_k}] \in \mathcal{B}(d_i;\, n_k\le i < n_{k+1})
\]
and hence $\{[l_{n_k}\ge r_{n_k}],\, k\ge 1\}$ are independent events. Use the Borel
Zero-One Law to show
\[
P([l_{n_k}\ge r_{n_k}]\ \text{i.o.})=1
\]
and hence
\[
P([l_n\ge r_n]\ \text{i.o.})=1.
\]

:::

### (a)
$\textbf{My idea:}$ Let $A_n=[d_{2n}=0]$, $B_n=[d_{2n+1}=1]$, by the Fact 3 in 4.3.2, $d_n$ are iid, so $\{A_n\}\cup\{B_n\}$ are independent since $A_n\in\sigma(d_{2n})$ and $B_n\in\sigma(d_{2n+1})$, therefore $\{\sigma(A_n)\}\cup\{\sigma(B_n)\}$ is an independent family of $\sigma$-fields since $\sigma(A_n)\subseteq\sigma(d_{2n})$ and $\sigma(B_n)\subseteq\sigma(d_{2n+1})$ and independence is preserved under taking sub-$\sigma$-fields, then by lemma 4.4.1 (Grouping Lemma), $\sigma(A_1,\dots,A_n,\dots)$ and $\sigma(B_1,\dots,B_n,\dots)$ are independent, and $A\in\sigma(A_1,\dots,A_n,\dots)$, $B\in\sigma(B_1,\dots,B_n,\dots)$, so $A$ and $B$ are independent.

$\textbf{Note:}$ The Grouping Lemma may be too strong for this question, we can also consider two random vectors $X=(d_2,d_4,\dots)$ and $Y=(d_1,d_3,\dots)$ are independent, and $A\in\sigma(X)$ and $B\in\sigma(Y)$.


### (b)
$\textbf{My idea:}$ Since $\{d_n\}$ are iid, and $P[d_n(\omega)=1]=P[d_n(\omega)=0]=\frac{1}{2}$, then we have 
$$
P[l_n=k]=P[d_n=0,d_{n+1}=0,\dots,d_{n+k-1}=0,d_{n+k}=1]=P[d_n=0]P[d_{n+1}=0]\dots P[d_{n+k-1}=0]P[d_{n+k}=1]=(\frac{1}{2})^{k+1},
$$
and since $\{l_n\geq r\}=\sum_{k=r}^\infty\{l_n=k\}$ (we use summation to express disjoin union here), we have
$$
P[l_n\geq r]=\sum_{k=r}^\infty P[l_n= k]=\sum_{k=r}^\infty(\frac{1}{2})^{k+1}=(\frac{1}{2})^{r}.
$$

### (c)
$\textbf{My idea:}$ $[l_n=0]=[d_n=1]$ and $\{d_n\}$ are iid ,so $\{[l_n=0],n\geq1\}$ are independent events.

### (d)
$\textbf{My idea:}$ According to (b) and (c), $\{[l_n=0],n\geq1\}$ are independent and $P[l_n=0]=\frac{1}{2}$, so $\sum_{n=1}^\infty P[l_n=0]=\sum_{n=1}^\infty\frac{1}{2}=\infty,$ so by Borel Zero-One Law, $P\{[l_n=0]\ \text{i.o.}\}=1$.

### (e)
$\textbf{My idea:}$ For $\{[l_n=1],n\geq1\}$, let's consider $[l_n=1]=[d_n=0,d_{n+1}=1]$ and $[l_{n+1}=1]=[d_{n+1}=0,d_{n+2}=1]$ for any fixed $n$, so $P\{[l_n=1]\cap[l_{n+1}=1]\}=P\{[d_n=0,d_{n+1}=1]\cap[d_{n+1}=0,d_{n+2}=1]\}=P(\emptyset)=0$,which is not equal to $P[d_n=0,d_{n+1}=1]P[d_{n+1}=0,d_{n+2}=1]=\frac{1}{2^4}$. For $\{[l_{2n}=1],n\geq1\}=\{[d_{2n}=0,d_{2n+1}=1],n\geq1\}$, these are disjoint events consist of independent events, so they are independent.

$\textbf{Answer:}$  For $\{[l_n=1],n\geq1\}$, let's consider $[l_n=1]=[d_n=0,d_{n+1}=1]$ and $[l_{n+1}=1]=[d_{n+1}=0,d_{n+2}=1]$ for any fixed $n$, so $P\{[l_n=1]\cap[l_{n+1}=1]\}=P\{[d_n=0,d_{n+1}=1]\cap[d_{n+1}=0,d_{n+2}=1]\}=P(\emptyset)=0$,which is not equal to $P[d_n=0,d_{n+1}=1]P[d_{n+1}=0,d_{n+2}=1]=\frac{1}{2^4}$. For $\{[l_{2n}=1],n\geq1\}=\{[d_{2n}=0,d_{2n+1}=1],n\geq1\}$,  then $[l_{2n}=1]\in\sigma(d_{2n},d_{2n+1})$, since $\{d_n\}$ are iid, then $\{\sigma(d_{2n},d_{2n+1}),\ n\geq1\}$ is a family of independent $\sigma$-fields, so $\{[l_{2n}=1]\}$ are independent, and we have $P[l_{2n}=1]=P[d_{2n}=0,d_{2n+1}=1]=\frac{1}{4}$, and $\sum_{n=1}^\infty P[l_{2n}=1]=\sum_{n=1}^\infty \frac{1}{4}=\infty$, by Borel Zero-One Law, we have $P([l_{2n}=1]\ \text{i.o.})=1$ and since $\{[l_{2n}=1]\ \text{i.o.}\}\subseteq\{[l_{n}=1]\ \text{i.o.}\}$, we have $P([l_{n}=1]\ \text{i.o.})=1$.

$\textbf{Note:}$ We shouldn't say $\{[d_{2n}=0,d_{2n+1}=1],n\geq1\}$ are disjoint, instead, we should use $\{\sigma(d_{2n},d_{2n+1})\}$ and the Grouping lemma to prove the independence. Also, I forgot the second part of this question when do my answer part.

### (f)
$\textbf{My idea:}$ We can firstly discuss $P[\limsup_{n\to\infty}\frac{l_n}{\log_2n}>1]$, because it is the probability of independent event in tail, which can only have value with $0$ or $1$ by Borel 0-1 law, and if it is $0$, then by $[\liminf_{n\to\infty}\frac{l_n}{\log_2n}>1]\subseteq[\limsup_{n\to\infty}\frac{l_n}{\log_2n}>1]$, we have $P[\liminf_{n\to\infty}\frac{l_n}{\log_2n}>1]\leq P[\limsup_{n\to\infty}\frac{l_n}{\log_2n}>1]=0$, so $P[\limsup_{n\to\infty}\frac{l_n}{\log_2n}\leq1]=1-P[\liminf_{n\to\infty}\frac{l_n}{\log_2n}>1]=1-0=1$. According to the definition of $\limsup$, if $\omega\in\{\omega\in\Omega:\ \limsup_{n\to\infty}\frac{l_n(\omega)}{\log_2n}>1\}$, then for any $\varepsilon>0$, exists $N(\omega)\geq1$ such that when $n\geq N$, we have $\frac{l_n}{\log_2n}>(1+\varepsilon)$ or $l_n>(1+\varepsilon)({\log_2n})$, and for large $n$, we also have $(1+\varepsilon)({\log_2n})\leq n$,by this inequality and the result from (b), we have
$$
\sum_{n\geq N}P[l_n>(1+\varepsilon)({\log_2n})]\leq\sum_{n\geq N} P[l_n>n]=\sum_{n\geq N}(\frac{1}{2})^{n+1}<\infty,
$$
then adding the finite terms before $N$, we have $\sum_{n}P[l_n>(1+\varepsilon)({\log_2n})]<\infty$ for arbitrary $\varepsilon$, so by letting $\varepsilon\to0$, that is $\sum_{n}P[l_n>\log_2n]<\infty$, so $P[\limsup_{n\to\infty}\frac{l_n}{\log_2n}\leq1]=1$.

$\textbf{Answer:}$ We can select a sequence $\{\varepsilon_k\}$, $\varepsilon_k\downarrow0$ and we have 
$$
\begin{aligned}
{}[\limsup_{n\to\infty}\frac{l_n}{\log_2n}>1]&=\bigcup_{k\geq1}[\frac{l_n}{\log_2n}>1+\varepsilon_k\ \text{i.o.}]\\
&=\bigcup_{k\geq1}[l_n>(1+\varepsilon_k){\log_2n}\ \text{i.o.}],
\end{aligned}
$$
for each $k$, by (b) we have 
$$
\begin{aligned}
\sum_{n} P[l_n>(1+\varepsilon_k){\log_2n}]&\leq\sum_{n}  P[l_n\geq(1+\varepsilon_k){\log_2n}]\\
&=\sum_{n} 2^{-(1+\varepsilon_k){\log_2n}}=\sum_{n} n^{-(1+\varepsilon_k)}<\infty,
\end{aligned}
$$
so according to Borel 0-1 Law, $P[l_n>(1+\varepsilon_k){\log_2n}\ \text{i.o.}]=0$ and
$$
\begin{aligned}
{} P[\limsup_{n\to\infty}\frac{l_n}{\log_2n}>1]&=P(\bigcup_{k\geq1}[l_n>(1+\varepsilon_k){\log_2n}\ \text{i.o.}])\\
&\leq\sum_{k\geq1}P([l_n>(1+\varepsilon_k){\log_2n}\ \text{i.o.}])\\
&=0.
\end{aligned}
$$
Therefore $P[\limsup_{n\to\infty}\frac{l_n}{\log_2n}\leq1]=1$.

$\textbf{Note:}$ We should get back to the definition of $\limsup$, for $\limsup_{n\to\infty}\frac{l_n}{\log_2n}>1$, it means that for any $\varepsilon>0$, $[\frac{l_n}{\log_2n}>1+\varepsilon]$ occur infinitely often, then use a countable sequence to express it.

### (g)
$\textbf{My idea:}$ I think the idea follows (e), that is divide $\{d_n\}$ into different chucks with disjoint index set, these index set should be constructed using $\log_2n$ to make sure we have a independent subsequence like $[l_{n_k}\geq\log_2n_{n_k}]$ are independent.

$\textbf{Answer:}$ Set $r_n=[\log_2 n]$, and define $n_k$ as $n_1=2, n_2=n_1+r_{n_1},\dots,n_{k+1}=n_k+r_{n_k}$, therefore, $n_{k+1}-n_{k}=r_{n_k}$. Since for each $k$, $[l_{n_k}\geq r_{n_k}]=[d_{n_k}=0,d_{n_k+1}=0,\dots,d_{n_{k}+r_{n_k}-1}=0]=[d_{n_k}=0,d_{n_k+1}=0,\dots,d_{n_{k+1}-1}=0]\in\sigma(d_i:n_k\leq i<n_{k+1})$, and by Grouping Lemma, events $\{[l_{n_k}\geq r_{n_k}],k\geq1\}$ are independent. and according to (e), 
$$
\begin{aligned}
P[l_{n_k}\geq r_{n_k}]&=2^{-r_{n_k}}\\
&=2^{-[\log_2n_k]}\geq\frac{1}{n_k},
\end{aligned}
$$
since $r_{n_k}=[\log_2n_k]\leq\log_2n_k$, so $n_{k+1}=n_k+[\log_2n_k]\leq n_k+\log_2n_k\leq2n_k$ for large $k$, and that is $\frac{1}{n_{k+1}}\geq\frac{1}{2}\cdot\frac{1}{n_k}$, by iterating, we have 
$$
\sum_{j=1}^m\frac{1}{n_j}\geq\frac{1}{n_m}\sum_{j=1}^m 2^{m-j}=\frac{2^m-1}{n_m},
$$
and $n_m\leq2^mn_1$, therefore $\sum_{k}P[l_{n_k}\geq r_{n_k}]\geq\sum_{k}\frac{1}{n_k}=\infty$, by Borel 0-1 Law, $P([l_{n_k}\geq r_{n_k}]\ \text{i.o.})=1$, and $\{[l_{n_k}\geq r_{n_k}]\ \text{i.o.}\}\subseteq\{[l_{n}\geq r_{n}]\ \text{i.o.}\}$, so $P([l_{n}\geq r_{n}]\ \text{i.o.})=1$.

$\textbf{Note:}$ This question stuck me for two days, firstly, if I follow the hint from the book by letting $n_1=1$, then we only have a constant subsequence, and then I made some concrete examples to display why disjoint blocks lead to independence: let's consider $[l_2\geq2]$ and $[l_4\geq3]$, so we have $P[l_2\geq2]=(\frac{1}{2})^2$ and $P[l_4\geq3]=(\frac{1}{2})^3$ and $P([l_2\geq2]\cap[l_4\geq3])=P(d_2=0,d_3=0,d_4=0,d_5=0,d_6=0)=(\frac{1}{2})^5=P[l_2\geq2]P[l_4\geq3]$, however, if we consider $[l_2\geq3]$ and $[l_4\geq3]$, then $P([l_2\geq3]\cap[l_4\geq3])=P(d_2=0,d_3=0,d_4=0,d_5=0,d_6=0)=(\frac{1}{2})^5\neq P[l_2\geq3]P[l_4\geq3]$, so this is what the hint means. Then the logic chain for this question is:

1. The original probability decreases at speed of $(1/2)^{n}$, so we need to construct a sub-sequence $n_k$ to draw $(1/2)^{-n_k}$ back to harmonic level, so we need the increment increases like $\log_2 n$,
2. Use it to construct a sequence of disjoint blocks,
3. Use these block to construct a sequence of independent events.

Besides: we can use $\int_{1}^\infty\frac{1}{x\log_2x}dx$ to prove the divergence.


## Ex 31

::: problem
Suppose $\{B_n,\, n\ge 1\}$ is a sequence of events such that for some $\delta>0$
\[
P(B_n)\ge \delta>0,
\]
for all $n\ge 1$. Show $\limsup_{n\to\infty} B_n \ne \varnothing$. Use this to help show with
minimum calculation that in an infinite sequence of independent Bernoulli trials, there is an
infinite number of successes with probability one.
:::

$\textbf{My idea:}$ Let $C_n=\bigcup_{n\geq k}B_k$, then $C_n$ is a decreasing sequence, and $P(C_n)=P(\bigcup_{n\geq k}B_k)\geq P(B_n)\geq\delta>0$, so $P(\limsup_{n\to\infty}B_n)=P(\bigcap_{n=1}^\infty\bigcup_{n\geq k}B_k)=\lim_{n\to\infty}P(C_n)\geq\delta>0$, so $P(\limsup_{n\to\infty}B_n)>0$, implying $\limsup_{n\to\infty}B_n\neq\varnothing$. For an infinite sequence of independent Bernoulli trials, that is, $X_n\sim\text{Bernoulli}(p_n)$, independent. Let $P(B_n)=p_n\geq\delta>0$, then $P(\limsup_{n\to\infty}B_n)>0$, since they are independent, by ~~Borel~~ **Kolmogorov** 0-1 Law, $P(\limsup_{n\to\infty}B_n)=1$, so there is an infinite number of successes with probability one.

$\textbf{Note:}$ Since we have construct a sequence of independent r.v, $\{X_n\}$, then we should note that $[B_n\ \text{i.o.}]$ is in tail, so we are using the Kolmogorov 0-1 Law, not the Borel one.

## Ex 32

::: problem
\noindent$\textbf{The Renyi representation.}$ Suppose $E_1,\ldots,E_n$ are iid exponentially
distributed random variables with parameter $\lambda>0$ so that
\[
P[E_1\le x]=1-e^{-\lambda x}, \qquad x>0.
\]
Let
\[
E_{1,n}\le E_{2,n}\le \cdots \le E_{n,n}
\]
be the order statistics. Prove the $n$ spacings
\[
E_{1,n},\ E_{2,n}-E_{1,n},\ \ldots,\ E_{n,n}-E_{n-1,n}
\]
are independent exponentially distributed random variables where $E_{k+1,n}-E_{k,n}$ has
parameter $(n-k)\lambda$. Intuitively, this results from the forgetfulness property of the
exponential distribution.
:::

$\textbf{My idea:}$ 
Let's express the order statistics as $E_{(1)},\dots,E_{(n)}$ for simplicity, I firstly try some simple cases: for $n=2$, it is a little trivial: $P[E_{(1)}>x]=P([E_{1}>x]\cap[E_{2}>x])=e^{-2\lambda x}$, and $P[E_{(2)}-E_{(1)}>x]=P(E_2-E_1>x|E_2>E_1)P(E_2>E_1)+P(E_1-E_2>x|E_1>E_2)P(E_1>E_2)$, then by forgetfulness of the exponential distribution, we have $P[E_{(2)}-E_{(1)}>x]=P(E_2>x)P(E_2>E_1)+P(E_1>x)P(E_1>E_2)=\frac{1}{2}e^{-\lambda x}+\frac{1}{2}e^{-\lambda x}=e^{-\lambda x}$. So for $n=1$, we can just discuss $P[E_{(2)}-E_{(1)}>x]$,
$$
\begin{aligned}
P[E_{(2)}-E_{(1)}>x]&=P(E_1-E_2>x|E_1=E_{(2)},E_2=E_{(1)})P(E_1=E_{(2)},E_2=E_{(1)})+\dots\\
&\qquad+P(E_3-E_2>x|E_3=E_{(2)},E_2=E_{(1)})P(E_3=E_{(2)},E_2=E_{(1)})\\
&=P(E_1-E_2>x|E_3>E_1>E_2)P(E_3>E_1>E_2)+\dots\\
&\qquad+P(E_3-E_2>x|E_1>E_3>E_2)P(E_1>E_3>E_2),
\end{aligned}
$$
by Renyi's therom, for each order, such as $E_1>E_3>E_2$, the probability is $1/n!=1/6$, and then what is 
$P(E_1-E_2>x|E_3>E_1>E_2)$?, Given $E_3>E_1>E_2$, when  $E_1-E_2>x$, there also have $E_3-E_2>x$, so it is just $P(E_1-E_2>x|E_3>E_1>E_2)=(e^{-\lambda x})^2=e^{-2\lambda x}$, then for $E_{(1)}$, we have, $P[E_{(1)}>x]=P[\min_{1\leq i\leq n}E_i>x]=P(\bigcap_{i=1}^n[E_i>x)=\prod_{i=1}^n P[E_i>x]=e^{-\lambda nx}$ since they are iid. Then for $E_{(k+1)}-E_{(k)}$, , we have 
$$
P(E_{(k+1)}-E_{(k)}>x)=\sum_{i\neq j}P(E_i-E_j>x|E_i=E_{(k+1)},E_j=E_{(k)})P(E_i=E_{(k+1)},E_j=E_{(k)})
$$
for $P(E_i-E_j>x|E_i=E_{(k+1)},E_j=E_{(k)})$, that is for each fixed order, $E_j$ is the $K$th rank, and since we are discussing  $P(E_{i}-E_{j}>x)$, than for each $E_k$ has higer rank, should also have $E_{k}-E_{j}>x$, and there are $(n-k)$ higer ranks, so using the forgetfulness and independence of $E_n$, we have $P(E_{(k+1)}-E_{(k)}>x)=\exp(-\lambda(n-k)x)$.

 
Renew 1: Let $T=\min_i E_i=E_{(1)}$ and $I=\arg\min E_i $, that is, $I$ is the index such that $E_I$ is $E_{(1)}$, then for $j\neq I$, we have 
$$
\begin{aligned}
P(E_j-T>x|T=t,I=i)&=P(E_j-E_i>x|E_i\ \text{is the minimum},E_i=t)\\
&=P(E_j>x+t|E_j>t)=P(E_j>x)=e^{-\lambda x}
\end{aligned}
$$
because since given $T=t$ and $E_j>T$, then it is $E_j>t$.

Renew 2:

We can rewrite $\{T=t,I=i\}$ as $\{E_i=t\}\bigcap_{k\neq i,j}\{E_k\geq t\}\cap\{E_j\geq t\}$, since $\{E_i\}$ are iid, so $\{E_j\geq t\}$ and $\{E_i=t\}\bigcap_{k\neq i,j}\{E_k\geq t\}$ are independent since they are in independent $\sigma$-field, which are $\sigma(E_j)$ and $\sigma(E_k:k=1,\dots,n\ \text{and}\ k\neq j)$, so

$$
\begin{aligned}
P(E_j-T>x|T=t,I=i)&=P(E_j>x+t|\{E_i=t\}\cap\bigcap_{k\neq i,j}\{E_k\geq t\}\cap\{E_j\geq t\})\\
&=\frac{P(\{E_j>x+t\}\cap\{E_i=t\}\cap\bigcap_{k\neq i,j}\{E_k\geq t\}\cap\{E_j\geq t\})}{P(\{E_i=t\}\cap\bigcap_{k\neq i,j}\{E_k\geq t\}\cap\{E_j\geq t\})}\\
&=\frac{P(\{E_j>x+t\}\cap\{E_i=t\}\cap\bigcap_{k\neq i,j}\{E_k\geq t\})}{P(\{E_i=t\}\cap\bigcap_{k\neq i,j}\{E_k\geq t\}\cap\{E_j\geq t\})}\qquad (\text{because }\{E_j>x+t\}\cap\{E_j\geq t\}=\{E_j>x+t\})\\
&=\frac{P(\{E_j>x+t\})\cdot P(\{E_i=t\}\cap\bigcap_{k\neq i,j}\{E_k\geq t\})}{P(\{E_i=t\}\cap\bigcap_{k\neq i,j}\{E_k\geq t\})\cdot P(\{E_j\geq t\})}\qquad (\text{Using independence})\\
&=\frac{P(E_j>x+t)}{P(E_j\geq t)}\\
&=P(E_j>x+t|E_j\geq t)=P(E_j>x)=e^{-\lambda x}
\end{aligned}
$$

$\textbf{Answer:}$ Let $E_{(1)}\le \cdots \le E_{(n)}$ be the order statistics. Then
\[
P(E_{(1)}>x)=P\Big(\min_{1\le i\le n}E_i>x\Big)=\prod_{i=1}^n P(E_i>x)=e^{-n\lambda x},
\]
so $E_{(1)}\sim\mathrm{Exp}(n\lambda)$.

Let $T:=E_{(1)}$ and let $I$ be the (a.s. unique) index of the minimum. Fix $t\ge0$ and
$\Delta>0$ and define
\[
A_{t,\Delta,i}:=\{t<T\le t+\Delta,\ I=i\},\qquad
G_\Delta:=\{t<E_i\le t+\Delta\}\cap\bigcap_{k\ne i,j}\{E_k>t\}.
\]
Then $A_{t,\Delta,i}=G_\Delta\cap\{E_j>t\}$, and $G_\Delta\in\sigma(E_k:k\ne j)$, hence $G_\Delta$
is independent of $\sigma(E_j)$. For $x\ge0$ and $j\ne i$,
\[
P(E_j-T>x\mid A_{t,\Delta,i})
= P(E_j>t+x\mid G_\Delta\cap\{E_j>t\})
= \frac{P(E_j>t+x)\,P(G_\Delta)}{P(E_j>t)\,P(G_\Delta)}
= \frac{P(E_j>t+x)}{P(E_j>t)}
= e^{-\lambda x},
\]
using $P(E>t+x)/P(E>t)=e^{-\lambda x}$ for $E\sim\mathrm{Exp}(\lambda)$. Similarly, for distinct
$j_1,\dots,j_m\ne i$,
\[
P\Big(\bigcap_{\ell=1}^m\{E_{j_\ell}-T>x_\ell\}\,\Big|\,A_{t,\Delta,i}\Big)
=\prod_{\ell=1}^m e^{-\lambda x_\ell},
\]
so the residuals $\{E_j-T: j\ne I\}$ are independent and $\mathrm{Exp}(\lambda)$.

Therefore,
\[
E_{(2)}-E_{(1)}=\min_{j\ne I}(E_j-T)\sim \mathrm{Exp}((n-1)\lambda).
\]
Iterating the same argument after removing the next minimum each time, the spacings
$E_{(1)},E_{(2)}-E_{(1)},\dots,E_{(n)}-E_{(n-1)}$ are independent and
\[
E_{(k+1)}-E_{(k)}\sim \mathrm{Exp}((n-k)\lambda),\qquad k=0,1,\dots,n-1,
\]
(with $E_{(0)}:=0$), i.e.\ the parameters are $n\lambda,(n-1)\lambda,\dots,\lambda$.

$\textbf{Note:}$ The formal conditional probability has not been introduced in this book yet, so at first I have to use some naive (not based on measure theory) probability method to deal with it, then in the end, I used the "hazard rate" method to make it as rigor as possible. Using the combination way is OK, but it will be a nightmare to write down the process and not fit the basic idea of measure theory, that is, the $\sigma$-field language.


